### ISSUE TITLE
Benchmarking x16r EnemyZealot for 20 minutes

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#10]
How long it takes to benchmark. in my miner its Benchmarking x16r EnemyZealot from 20 minutes

**Comment by RainbowMiner** [comment]
Hi, this is normal behaviour. Since X16r deviates a lot over time, the miner needs some time to find a good median value for profit comparision. I did setup the X16r miners with a minimum of 10 times the normal waiting period. Luckily, you only have to go through this waiting time once. I  did setup the RainbowMiner, so that the long lasting benchmarks will all be done at first. If they are done, the benchmarks for all the other algorithm miners will start.

If you feel, this is too long for you, let me know :)

RBM

**Comment by rinkal26783** [comment]
Yes, I think 20 minutes is to much for any benchmark. I think 5 minutes should be the highest benchmark time.

**Comment by RainbowMiner** [comment]
I reduced the X16r benchmarking time to 5 times (this will result in absolute benchmark times of 5-10 minutes at maximum).
