### ISSUE TITLE
BTC addresses too long

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1013]
When using the powershell menus to change the BTC address, there is a character limit that prevents some valid BTC addresses. Enter those addresses manually in the config file works as a temporary work around....

![image](https://user-images.githubusercontent.com/42582444/83146291-f8cb7c80-a0ed-11ea-9ea6-49027cff9a8e.png)

**Comment by RainbowMiner** [comment]
Yes, that's a problem of compatibility - there are some pools that do not accept the bech32 BTC notation thus causing trouble. For that reason I have still restricted the input to 34 characters (the "old" BTC notation with "1" or "3" at the beginning of the wallet address).

Since ZergPool seems to be ok with bech32, now, I will try to figure out, which pools cause the trouble.

**Comment by RainbowMiner** [comment]
bech32 addresses are allowed now. But please check, if you selection of pools do really support the bech32 format.
