### ISSUE TITLE
SrbMiner-Multi Linux...can't boot in RBM! works standalone!

### ISSUE THREAD

**Issue by ArSd-g** [RainbowMiner/RainbowMiner#1022]
![Capture d’écran du 2020-06-02 08-21-39](https://user-images.githubusercontent.com/42816950/83487498-6e976580-a4ab-11ea-805f-fcafaf8861e2.png)
![Capture d’écran du 2020-06-02 08-29-51](https://user-images.githubusercontent.com/42816950/83487504-735c1980-a4ab-11ea-9eff-9a5cf3cd829d.png)

**Comment by RainbowMiner** [comment]
It seems to crash in both cases, because it looks like SrbMiner-MULTI isn't compatible with Nicehash. I will exclude ethash.

**Comment by RainbowMiner** [comment]
Could you look up and eventually upload the `SrbMinerMulti-GPU#*` log files in `.\Logs` folder?

**Comment by ArSd-g** [comment]
no that your generated *.sh the problem (PATH??) 
The very last command in your *sh (=to start miner) works if run from SRBMiner root directory...as (simple copy past...log are empties btw) 
sudo ./SRBMiner-MULTI --algorithm yespower2b --api-enable --api-port 34901 --api-rig-name ArScl --disable-gpu --cpu-threads 2 --cpu-affinity 0x0005 --pool power2b.mine.zergpool.com:7445 --wallet MLhC2HEqjBsN2z1RPkJYR9BbMZ4HrCpQRs --worker ArSclcpu --password ArSclcpu,c=LTC --tls false --nicehash false --keepalive --retry-time 10 --disable-startup-monitor

**Comment by ArSd-g** [comment]
1st test was on archlinux-zen-kernel with intel G4600
here it's ubuntu-server-lts-hwe-kernel with 2xXeon-E5-2658V3
=same!
![Capture d’écran du 2020-06-04 08-39-40](https://user-images.githubusercontent.com/42816950/83723584-39238100-a63f-11ea-8c82-8a2bf22c19a3.png)

**Comment by RainbowMiner** [comment]
I have launched a linux server on Ubuntu 18 to see, if something is off with srbminer. One thing I have noticed: you are running everything as root (through sudo). That might cause trouble. 

Actually, you might want to reinstall RainbowMiner into another folder, just to see if running RainbowMiner with your default user account solves the problems.
That's pretty easy:
1. run your current instance, open http://localhost:4000 (or your machines IP http://your.ip.address:4000)
2. click on "Get setup.json"
3. edit the "AutoStart" section in setup.json to your needs. Most importantly set `"Enable": "1",` and enter a WorkerName for that machine `"WorkerName": "whateveryoulike",`. You might also want to eventually edit "DeviceName" to match your machine.
```
  "Autostart": {
    "Enable": "1",
    "ConfigName": "All",
    "DeviceName": "CPU",
    "WorkerName": "novax"
  },
```
4. now unzip or clone a new RainbowMiner into another folder
5. `chmod +x *sh` in the new folder
6. run `sudo install.sh` (as root!) 
7. copy that setup.json into the new RainbowMiner folder
8. now start RainbowMiner `./start.sh` or `./start-screen.sh` (not root, but with your user account)

.. unfortunately you will have to run all the benchmarks again. Since they have been written through a "root" (sudo) instance in your old folder, it's very complicated to copy them into a non-root instance.

**Comment by RainbowMiner** [comment]
> I have launched a linux server on Ubuntu 18 to see, if something is off with srbminer.

Oh! I think, I can reproduce the problem! Will report back asap.

**Comment by RainbowMiner** [comment]
Wow. Very good finding and thank you so much for reporting this. The issue is now solved. I will push a new release today (which will automatically restart all benchmarks for SrbMinerMulti, if on linux)

**Comment by ArSd-g** [comment]
np...glad it fix! do you think is better to run RBM as user with runMinerAsRoot : 1 parameter?
also don't forget amdgpu-oc-linux (just to remind) and especially the ability to run scripts before/after miner/algo start!

**Comment by RainbowMiner** [comment]
> do you think is better to run RBM as user with runMinerAsRoot : 1 parameter?

If you did run the `./install.sh` script, at the beginning, there should be a daemon running in the background, that will start every script and miner as root. In case the daemon is up-and-running, running, you can simply run RainbowMiner as non-root user (which in fact avoids a lot of hassle with access rights and of course removes the need to "sudo" everything).

To check, if the daemon is up-and-running, open a shell and type `ocdaemon status` - if it says `running`, you are good.

**Comment by RainbowMiner** [comment]
And, of course you are right, set "EnableMinersAsRoot": "1",. Otherwise the miners will not be sent to the ocdaemon.
