### ISSUE TITLE
Question: Pool accuracy weight

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1050]
Does this option reduce the effect of the profit switcher? So the default of 15 means the threshold for switching is reduced by 85%?

**Comment by RainbowMiner** [comment]
> PoolAccuracyWeight = adjust weight of pool accuracy on the profit comparison in % (0..100, 0=disable) [default=15]


The profit switcher can be controlled like follows. To be able to compare the pools (a "pool" is basically each available PoolName+Algorithm+CoinSymbol), an internal comparison price is being calculated.
- PFC is the price for comparison. It starts at the current pools price
- all available config parameters are marked as **bold**
- if **EnableFastSwitching** is set to "0" (=disabled) in config.txt:
  - for Pools, that _aren't_ currently being mined, comparison prices will be _decreased_
    - PFC = PFC x ( 1 - ErrorMargin(%)/100 x DecayFactor(t) x **PoolAccuracyWeight(%)**/100 )
  - for Pools, that _are_ currently being mined, comparison prices will be _increased_
    - if `SwitchingHysteresis` is set in pools.config.txt
      - PFC = PFC x ( 1 + **SwitchingHysteresis(%)**/100 )
    - else if `PoolSwitchingHysteresis` is set in config.txt
      - PFC = PFC x ( 1 + **PoolSwitchingHysteresis(%)**/100 )
- all prices will be decreased by a reverse exponential function, that will set hashrates into comparison to the maximum possible Algorithm+CoinSymbol hashrates
  PFC = PFC x ( 1 - (1 - (Hashrate/MaximumHashrate(Algorithm+CoinSymbol))^(**HashrateWeightStrength(%)**/100)) x (**HashrateWeight(%)**/100) )
- if **MaxAllowedLuck** is set to a value greater than 0
  - PFC = PFC / (PoolLuck - **MaxAllowedLuck** + 1)
- if **MaxTimeSinceLastBlock** is greater than 0 and the pool's time since last block is greater than **MaxTimeSinceLastBlock**, the comparison price will be decreased:
  - PFC =  PFC / ( (PoolTimeSinceLastBlock - **MaxTimeSinceLastBlock**)/3600 + 1 )
- all prices will be decreased by an inverse logarithmic function, depending on how far a pool is out of sync (current-time minus last-price-or-hashrate-update time)

**Comment by RainbowMiner** [comment]
> Does this option reduce the effect of the profit switcher? So the default of 15 means the threshold for switching is reduced by 85%?

So, the answer is yes :)

**Comment by RainbowMiner** [comment]
Sorry, for my rather technical answer, but the pool profit switcher is really a beast.

**Comment by acos0874** [comment]
Thanks for the in depth explanation. I was finding that with a high switch prevention figure, I would sometimes be mining some very volatile and unprofitable algos still. It didn't make sense to me that an algo with 70% accuracy and switch prevention 5 would ever get mined at all. Now I have switched to using 100% pool accuracy weight with switch prevention 3 and a maxmarginoferror on nicehash of 5% and it is giving me a good time on each pool. My reasoning is that this effectively creates a 15% threshold for switching to an algo that isn't the current one. For other algos on other pools with a lower accuracy the threshold would be higher.
