### ISSUE TITLE
Drop Down Menu on "See How Others Are Doing" at Monitoring Central

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1055]
Just curious if there was a need to get rid of the drop down menu.  I actually like being able to choose different cards that I don't own to see how they are doing.  Same goes for different algos, many times I'll notice algos that I've never heard of before.  Same goes for mining software, I used to pull down the drop down menu and see different kinds of software that I've never come across.  Anyway I know this is not a pressing issue, just curious....

**Comment by RainbowMiner** [comment]
Yes, there was a need for that. Bootstrap tables have a problem with online-paging and dropdowns. Since the total database has reached an enormous size, I needed to switch from download-all to download-pagewise. With the drawback, that I needed to exchange the dropdown fields with input fields.
Actually, I could add some information lists for cards, algos and mining software.

**Comment by jch9678** [comment]
That would be cool.  Anything is appreciated.
