### ISSUE TITLE
CPU Affinity Questions Regarding Remote Monitoring

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1109]
In order for Remote Monitoring to work properly on my Ryzen machines I have to set EnableAutoAdjustAffinity to true.  If I use all cores, RM is just not able to keep up with reporting information.  Some times it can't even capture the hashrate from the mining software itself and reports a '0 hashrate is outside the tolerance and will not be updated' or something to that effect.  

My first question is, is there any other way to get reporting to work while using all cores without having to resort to disabling a core?

My second question has to do with having these 3 options in the config, enabling autoadjust disables a core but if I change the other options how will that affect the number of cores used.  If there's no other solution to reporting to Remote Monitoring than to disable some resources, I'm thinking disabling a full core is overkill, and we only need to disable a thread.  Is that possible?  I've manually changed an xmrig config file to use 23 threads out of 24 (instead of 22 out of 24 with autoadjust) and it worked fine, 1 thread handled reporting.

"EnableAutoAdjustAffinity": "1",
"CPUMiningThreads": 24,
"CPUMiningAffinity": "0xFFFFFF",

Coincidentally one of my machines that I set autoadjust to true has stopped reporting to RM and the local dashboard is reporting a 0 hashrate even though the miner is still running fine.  I have attached it's debug file.
[debug_2020-07-26.zip](https://github.com/RainbowMiner/RainbowMiner/files/4978343/debug_2020-07-26.zip)

**Comment by RainbowMiner** [comment]
> I'm thinking disabling a full core is overkill, and we only need to disable a thread. Is that possible?

Yes, having all threads stuck up in mining will slow down the machine to a crawl. In my experience it is best to keep two threads for the system to continue working. `EnableAutoAdjustAffinity` will do it's adjustment only, if all threads are selected, using CPUMiningAffinity.

My best guess for you system would be to set
```
"EnableAutoAdjustAffinity": "0",
"CPUMiningThreads": 22,
"CPUMiningAffinity": "0xFFFFF5",
```

.. this leaves two threads to the system, but all cores (plus 10 threads) for mining.

**Comment by jch9678** [comment]
I think your suggestion disables 1 core for mining....for your example shouldn't I use

"EnableAutoAdjustAffinity": "0",
"CPUMiningThreads": 22,            <--------------- leaves 2 threads to the system
"CPUMiningAffinity": "0xFFFFFF",    <------------ all 12 cores available

Do all cpu miners have affinity and thread parameters?  If one doesn't use threads then it will see all cores available.

Did you get a chance to see the debug file for a computer that stopped responding to RM while still mining?

**Comment by RainbowMiner** [comment]
The affinity is a bitmask, where all even bits are connected to a real core, all odd bits to a core's extra thread. The CPUMiningThreads tells a miner how many calculation threads will be used. If the CPUMiningAffinity mask bit count doesn't match the CPUMiningThreads, each miner will try to distribute the threads differently. That is why the CPUMiningThreads should equal to the positive bitcount in CPUMiningAffinity (leaves no room for misinterpretation within the miner's software).

This is how FFFFF5 looks like in binary:

`1111 1111 1111 1111 1111 0101` 

Since the bits are counted from right to left, you have enabled the follwoing on your CPU:

0: Core 0/Thread 0 = enabled
1: Core 0/Thread 1 = disabled <--
2: Core 1/Thread 0 = enabled
3: Core 1/Thread 1 = disabled <--

4: Core 2/Thread 0 = enabled
5: Core 2/Thread 1 = enabled
6: Core 3/Thread 0 = enabled
7: Core 3/Thread 1 = enabled

8: Core 2/Thread 0 = enabled
9: Core 2/Thread 1 = enabled
10: Core 3/Thread 0 = enabled
11: Core 3/Thread 1 = enabled

12: Core 2/Thread 0 = enabled
13: Core 2/Thread 1 = enabled
14: Core 3/Thread 0 = enabled
15: Core 3/Thread 1 = enabled

16: Core 4/Thread 0 = enabled
17: Core 4/Thread 1 = enabled
18: Core 5/Thread 0 = enabled
19: Core 5/Thread 1 = enabled

20: Core 6/Thread 0 = enabled
21: Core 6/Thread 1 = enabled
22: Core 7/Thread 0 = enabled
23: Core 7/Thread 1 = enabled

With this config, you have disabled the extra "Thread 1" of "Core 0" and "Core 1", but the main "Thread 0" will be be used by the miner. Your system should run stable enough on these two threads.

**Comment by jch9678** [comment]
Thank you again, I'm learning so much.  I'm sure I will go with your suggestion but just for my own education and maybe a test later could I do this:

"EnableAutoAdjustAffinity": "0",
"CPUMiningThreads": 23, 
"CPUMiningAffinity": "0xFFFFFD",

Which would be

1111 1111 1111 1111 1111 1101

0: Core 0/Thread 0 = enabled
1: Core 0/Thread 1 = disabled <--
2: Core 1/Thread 0 = enabled
3: Core 1/Thread 1 = enabled

4: Core 2/Thread 0 = enabled
5: Core 2/Thread 1 = enabled
6: Core 3/Thread 0 = enabled
7: Core 3/Thread 1 = enabled

8: Core 4/Thread 0 = enabled
9: Core 4/Thread 1 = enabled
10: Core 5/Thread 0 = enabled
11: Core 5/Thread 1 = enabled

12: Core 6/Thread 0 = enabled
13: Core 6/Thread 1 = enabled
14: Core 7/Thread 0 = enabled
15: Core 7/Thread 1 = enabled

16: Core 8/Thread 0 = enabled
17: Core 8/Thread 1 = enabled
18: Core 9/Thread 0 = enabled
19: Core 9/Thread 1 = enabled

20: Core 10/Thread 0 = enabled
21: Core 10/Thread 1 = enabled
22: Core 11/Thread 0 = enabled
23: Core 11/Thread 1 = enabled

**Comment by RainbowMiner** [comment]
Sure, the values are correct and one thread sometimes is sufficient.

**Comment by jch9678** [comment]
I tested it, and xmrig with heavyxhv didn't seem to work.  It works with your suggestion however.
