### ISSUE TITLE
CPU or GPU Appended to Worker Name

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#1111]
I'm not sure which version started doing this but cpu or gpu is appended to the worker name at the pools.
It looks like this at the pools, WorkerNamecpu
[debug_2020-07-26.zip](https://github.com/RainbowMiner/RainbowMiner/files/4978399/debug_2020-07-26.zip)

**Comment by RainbowMiner** [comment]
Could you please upload your devices.config.txt here?

**Comment by jch9678** [comment]
[devices.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/4985311/devices.config.txt)

**Comment by Kjwon15** [comment]
Me too. it shown on pool as "workernamecpu" but not gpu

**Comment by RainbowMiner** [comment]
Hi, this is intended behavior. I automatically add a "cpu" to the default workername, so that CPU mining can be easily distinguished from GPU mining. This plays a major role, when using MiningRigRentals. With this, it is possible to separately rent out CPU and GPU. It is possible to change this - just put the workername into the devices.config.txt (parameter "Worker" in CPU section). Then, RainbowMiner will use that name.
