### ISSUE TITLE
Renting only CPU or GPU?

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1116]
Is there a way to only rent CPU or GPU on a machine? Leaving the other devices not rented to follow normal script auto switching?

**Comment by RainbowMiner** [comment]
Hi, this is already possible. You have the following two settings in pools.config.txt:
```
    "ExcludeWorkerName": "",
    "UseWorkerName": "",
```
.. select which WorkerName to exclude from MiningRigRentals in ExcludeWorkerName or define which workername(s) to use exclusively for MiningRigRentals in UseWorkerName. If you haven't defined otherwise (in devices.config.txt), your CPU's workername is your rig's workername extended with "cpu".
E.g. if you rig's username is "rainbowminer", your CPU's workername will be "rainbowminercpu".

**Comment by Yamanipanuchi** [comment]
Yup, I see it now. Thanks!
