### ISSUE TITLE
Bug: miner.config has left over MSIprofiles

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#112]
Just a FYI the miners.config came with some MSIprofiles preset randomly again. Probably from your own testing assume. Just need them clear for new downloads.

**Comment by RainbowMiner** [comment]
Yes, I prefilled them for easy setup, so that users can download, follow my MSI recommendations and all will be fine. I would like to leave this, because some user really appreciate the easy head start.

Since the config files are all created at the first run of "Start.bat", I could provide you with an extra command "RemovePresets.bat". You would have to run this before the first run of "Start.bat" and all presets would be ignored. Would this be ok?

**Comment by Byrd1083** [comment]
Great compromise thanks. 👍
