### ISSUE TITLE
Q&A: Switching prevention

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#114]
This was always such a hot debat about how switching prevention works. Over at MPM it is so confusing. Could you break it down for us viewers out there on what kind of effects will happen while changing this value. How does it decide when to switch? I there an time limit for switching. For example if I set it to 10, what would be the expected results versus 2 or 5. Why is 2 optimal?

**Comment by Byrd1083** [comment]
Currently I have stock setting of 2 and it is switching more then I would like. I am changing anywhere from 60~180 secs back and forth between miners. Ideally I would like to be able to mine an algo for at least 30 ~ 60 minuets before a switch regardless of coinbase prices. It seems like it is currently switching with spikes in prices.

[config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2351249/config.txt)
[RainbowMiner_2018-09-04.txt](https://github.com/RainbowMiner/RainbowMiner/files/2351252/RainbowMiner_2018-09-04.txt)

**Comment by RainbowMiner** [comment]
Ok, this will take a little to write it down. There are many options, that you may adjust to reduce switching.

Basicly for the beginning:
- what I can recommend as first-aid kit: I would reduce the pools used. Just pick some proven to be stable and good paying pools and do not use ZergPoolCoins and MiningPoolHubCoins if you just want autoexchange mining.
- give it some time, because RainbowMiner uses a weekly (downto three days) average for comparision of the pools. So in the beginning there might be a lot of switching, but this will reduce over time.
- also, RainbowMiner keeps track of the individual price swings and includes the amplitude of the swings into it's calculation
