### ISSUE TITLE
Enhancement: GUI

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#118]
I know not everyone likes it but some people love GUI and may choose to use your program over the next if you provide one as beautiful as a rainbow lol. 

Maybe a future Rainbow V4 will provide an option at setup to choose to either use a gui or powershell. I have played around with nemosminer if you have ever heard of it. It has a very basic, not so pretty, GUI you can check out to get ideas from.😎

https://github.com/nemosminer

FYI, I can do web development/design, graphics editing. Just that java is not my strong point. I can help design the GUI graphics if you ever feel like going that far. Imagine being able to make all these custom profile configs through a single gui window versus 3~5 independent windows all over the place. It can get crazy 😨

**Comment by Byrd1083** [comment]
Not plugging but I'm also an owner of a plumbing company. Here is my site I built for example http://www.plumbingwa.com 

I study SEO and have great results managing everything on my own.

**Comment by Byrd1083** [comment]
Oh ya, I service and install boilers and self taught mechanic with a bad ass Ford 98 cobra 32v 🚀

**Comment by RainbowMiner** [comment]
🥇  .. nice ford! I like it :D

The GUI is already something I am thinking about a lot. My plan would be to not use powershell/windows for that, because it is kind of, well, awkward. I tend to put everything into the http://localhost:4000, so that everything can be setup there. My other way to go is a little more expensive, thus thinking about putting everything into a C# program.
So or so: I could definetly need some help.
