### ISSUE TITLE
Equihash96 errors

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1198]
In the past when I've tried to mine equihash96 on zpool it's always failed. I just picked up a well paying equihash96 rental but it's giving all rejected shares. I was wondering if you could please check if it's an RBM problem or a renter problem?

**Comment by RainbowMiner** [comment]
I had some Equihash 96 rental, some days ago. It went through fine, so I suspect, it's a renter issue.

**Comment by acos0874** [comment]
OK

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/95523395-6c4b9780-09c6-11eb-934e-4910c9b5ae70.png)
Pretty sure there's an issue here. This is running a benchmark.

**Comment by RainbowMiner** [comment]
Yes, looks like Zpool has some incompatible coin on that algorithm, at first glance. But I'll better look into it.

**Comment by RainbowMiner** [comment]
Is this the Ewbf miner?

**Comment by acos0874** [comment]
It's gminer on linux. I just noticed miniz benchmarked fine. Might be due to some personalisation issue since I think GLT or some other coins switched.

**Comment by RainbowMiner** [comment]
Ok, that explains the difference: my rig prefers MiniZ for Equihash 96,5 - it is (was) the only miner pre-configured for pers auto (which is needed for GLT mining). I have now reconfigured Gminer and EWBF, so that both of them should be able to mine on Zpool without rejected shares. Thank you for re-opening this thread.

**Comment by acos0874** [comment]
Thanks for fixing!
