### ISSUE TITLE
Benchmarks combo mode, not all combinations are being benchmark

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#125]
When using mining combo mode not all combinations are being benchmark. if you try to remove it, there is nothing to remove, if you want to delete it manually the stat file is not physically in the folder. 

![image](https://user-images.githubusercontent.com/41829368/45151781-80d85880-b18c-11e8-9c73-7fbb750fa1ac.png)

**Comment by RainbowMiner** [comment]
This is normal. I should either remove combos from the banchmark page, where no stat file exists (or mark them explicitly).

RainbowMiner does not benchmark all possible combos, because that would take way much too long. Instead it benches all groups on their own and then creates a virtual combo statistic in memory. At the time the combo is being selected and mined for the first time, a statistic file will be created. If a combo has never been run, no stat file will exist.

RBM

**Comment by hernandn01** [comment]
Makes sense. What makes all combos to benchmark? I have seen them run all combinations before but not lately.

**Comment by hernandn01** [comment]
I don't mind the time it take to benchmark, maybe a setting to allow all benchmarks? On that note, what is the Legacy mining mode?

**Comment by hernandn01** [comment]
Weird, now is showing two. I haven't done any changes. Just wondering why is not showing all information available

![image](https://user-images.githubusercontent.com/41829368/45169341-a8deb080-b1ba-11e8-8222-018a87bd1f29.png)

**Comment by RainbowMiner** [comment]
> I don't mind the time it take to benchmark, maybe a setting to allow all benchmarks? On that note, what is the Legacy mining mode?

Ok. I will program a switch, so that all Combos can be mined. Legacy is the simplest way of selection. Only one Miner will mine all GPU together. Even if they are different.

**Comment by hernandn01** [comment]
All combinations are benchmarking, tested Legacy, Device and Combo, Thanks
