### ISSUE TITLE
enhancement to start-screen.sh

### ISSUE THREAD

**Issue by gurkburk76** [RainbowMiner/RainbowMiner#1298]
I was thinking of that i could start my rig via home assistant when X amount of power is generated (i have solar panels) so i started fiddeling with a script for that, i realised that i can start it with start-screen.sh and kill it with stopp.sh but the start-screen.sh needs a tiny tweak as not to start several instances.
I don't know git well enough to actually to a pull request so i'll just paste it here, this should work i think. you might want to tweak it further so it get added to the logs if the else statement actually kicks in :)

#!/usr/bin/env bash

cd "$(dirname "$0")"

if ! screen -list | grep -qi "rainbowminer"; then
        # run bash script
        screen -S RainbowMiner -d -m ./start.sh
else
        echo "screen already running!"
fi

I guess it would be cool(er) to be able to do this via api/rest, but this will do :)

**Comment by RainbowMiner** [comment]
Good idea. It will need some more improvement, since it's allowed to run multiple instances of RainbowMiner on one machine. I will have a look.

**Comment by RainbowMiner** [comment]
Actually, you could make use of the pause function of RainbowMiner. Of course, there would be still a little more power consumption, in comparison to full stop.

It can be set/reset via the API.
There are the following URLs avail:

- `http://localhost:4000/status` : Shows the status of mining
  Result:
```
{
  "Pause": false,
  "LockMiners": {
    "Locked": false,
    "Enabled": false,
    "Pools": []
  },
  "IsExclusiveRun": true,
  "IsDonationRun": false
}
```
- `http://localhost:4000/pause` : toggle Pause status

.. to help with that, I have just added a new commit (3fe5979fb516d8ab911ddd90334904d67b9b144d), so that you can set/reset the Pause mode directly. So no need to read status and then toggle status.
- `http://localhost:4000/pause?action=set` : set (or continue to pause) Pause mode
- `http://localhost:4000/pause?action=reset` : end (or continue to run) Pause mode.

In case RainbowMiner is up and running, these URLs could be easily used via simple `wget` command.

To send RainbowMiner into Pause mode:
`wget http://localhost:4000/pause?action=set`

To let RainbowMiner from the leash:
`wget http://localhost:4000/pause?action=reset`

**Comment by gurkburk76** [comment]
Sounds good to me, as long as it's not mining the powerdraw is fully acceptable.

Just a small comment, perhaps these commands would be slighty more clear?
http://localhost:4000/pause?action=pause
http://localhost:4000/pause?action=unpause

**Comment by RainbowMiner** [comment]
Sure, I'll add "pause" and "unpause" as synonyms.
