### ISSUE TITLE
HeroMiners shows no profit

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1301]
Is this a bug, or do I need to tweek my settings?
![image](https://user-images.githubusercontent.com/4724631/104272465-03a30980-5452-11eb-8d48-1b7ffae6a4b4.png)

HeroMiners shows up 0 for profitablity.

**Comment by RainbowMiner** [comment]
Thank you for pointing it out. It should show a profit. I'll check asap.

**Comment by Yamanipanuchi** [comment]
Noticed it for ETH and XMR on HeroMiners.

**Comment by Yamanipanuchi** [comment]
Not sure if this is anything to add, But when it does show a number on a system it still does not mine it.

![image](https://user-images.githubusercontent.com/4724631/104326161-3ffc5700-549e-11eb-8cf0-d6bfed9aafcb.png)

HeroMiner shows a higher BTC/Gh/Day yet it still favors Nicehash.

**Comment by Yamanipanuchi** [comment]
Once I remove the MaxTimeSinceLastBlock for that pool the numbers show up correctly and HeroMiners looks to be more profitable in the "All Pools" tab but Nicehash is still favored. I cant seem to see why.

**Comment by Yamanipanuchi** [comment]
[debug_2021-01-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/5803320/debug_2021-01-12.zip)

Debug from one of the systems that theoretically would be mining HeroMiner/ETH but is not. Just in case it might help.

**Comment by RainbowMiner** [comment]
Ahh! Sure. That's the reason: RainbowMiner takes care about pools, that do not find blocks in time. The profitability is degraded more and more, the longer ago the last block has been found. Also, it might be the case, that the pool is out of sync.
There are the formulas:
- if **MaxAllowedLuck** is set to a value greater than 0
  - PFC = PFC / (PoolLuck - **MaxAllowedLuck** + 1)
- if **MaxTimeSinceLastBlock** is greater than 0 and the pool's time since last block is greater than **MaxTimeSinceLastBlock**, the comparison price will be decreased:
  - PFC =  PFC / ( (PoolTimeSinceLastBlock - **MaxTimeSinceLastBlock**)/3600 + 1 )
- all prices will be decreased by an inverse logarithmic function, depending on how far a pool is out of sync (current-time minus last-price-or-hashrate-update time)

**Comment by RainbowMiner** [comment]
My conclusion: do not mine to a pool, that needs long to find a block. It will decrease your profitability significantly.

**Comment by Yamanipanuchi** [comment]
Makes sense. and that is what I suspected it to be. If I wanted to force RBM to mine on Hero for ETH, What would I want to modify?

**Comment by rizkyaulya** [comment]
![image](https://user-images.githubusercontent.com/44210627/107037711-0a713200-67ee-11eb-9bf9-1ad239de24fb.png)

Conceal hardforked to CN GPU,
haven't update yet on rbminer

**Comment by RainbowMiner** [comment]
Thank you! These fork information is very helpful. I'll update the coins database asap.

**Comment by RainbowMiner** [comment]
Ok, database is updated.
