### ISSUE TITLE
nicehash and private keys

### ISSUE THREAD

**Issue by gurkburk76** [RainbowMiner/RainbowMiner#1313]
So i'm giving nicehash a try, i've created a api key and inputed the things the scripts ask me for, like private key, org number etc but it seems like it will happily mine away and work as intended even if i onöy have my nicehash btw wallet there.
So my question is, why should i input these things? What i'm i missing ? :)

If this is not the place for "support" like this please point me to a better place for it. I've join discord but unsure if you actually are there or if it's just a bot that publishes the latest changes/releases.

**Comment by RainbowMiner** [comment]
This is the right place for support 👍 
- For mining on Nicehash, it's sufficient to supply their BTC mining wallet address in pools.config.txt
- if you want to see your current balance in RainbowMiner, you will have to supply your API Keys and Org number.

**Comment by gurkburk76** [comment]
Ah ok, must be this then:
Nicehash      BTC  0.00072368 0.00000907 0.00072368 27.33
(yey i'm rich!!!)
Possible to add to https://rbminer.net/monitoring or would that open for others to find/exploit ?

**Comment by RainbowMiner** [comment]
One very important remark: you should always use your Nicehash Mining Wallet Address as given by Nicehash in pools.config.txt - otherwise it will mine to your default BTC wallet address in config.txt. That's ok, but will cost you a high fee, in case you want to move your funds off from Nicehash. If you use the NH Mining Wallet in pools.config.txt, you have the option to send your funds to Coinbase for zero fee.

**Comment by gurkburk76** [comment]
Yes, thanks for the support :)
