### ISSUE TITLE
Would P2 state off, help 3080 crash

### ISSUE THREAD

**Issue by cathos93** [RainbowMiner/RainbowMiner#1354]
Hi,
I've been using T-rex miner with rtx 3080FE , noticed that after few hours (6-8) mining at 99mh/s with 211W at 51c it suddenly crashes, reverses all settings done in MSI afterburner ( 0core , 1100mem, 67 PL). 
Does P2 state turned off would matter for 30xx series as for 1080?

**Comment by RainbowMiner** [comment]
If it's Windows, it may help, yes. I had similar problems with my RTX3070 GPUs.

**Comment by cathos93** [comment]
> If it's Windows, it may help, yes. I had similar problems with my RTX3070 GPUs.

did You tweak anything else ? it's running stable after OC is restored back to what i set. Just afraid it ll happen again when im away from rigs for longer period of time. 
Thanks for reply !

**Comment by RainbowMiner** [comment]
> did You tweak anything else?

No, just that "Force P2 State". That did help. My overclocking is not that much on the edge:

PL | Core | Mem
-- | -- | --
80 % | 100 | 1000

Also, currently, I get better results on the pool with Gminer.

**Comment by RainbowMiner** [comment]
> Just afraid it ll happen again when im away from rigs for longer period of time.

I recommend adding a Sonoff power plug or similar, so that you can power off/on your machine from remote, at any time. You just have to make sure, that you setup the BIOS, such that it starts the machine on power on.

Actually, all my rigs have a two-step aide. One is a Sonoff switch, that is connected in parallel to the reset switch. This is the one I use most frequently, if a rig gets stuck. The second is a Sonoff power plug to do power off/on, in case the reset switch should fail (never happend in the past three years).
