### ISSUE TITLE
Stats file not updating

### ISSUE THREAD

**Issue by talentoscope** [RainbowMiner/RainbowMiner#1355]
Not sure what's changed in my system (probably doing less heavy work on here recently), but the stat files are not updating due to being well outside the tolerances.

![image](https://user-images.githubusercontent.com/22162766/105767311-d1fe6800-5f52-11eb-8100-a85e385050cf.png)

I know they're in there for a good reason, but is it possible to change the tolerances to 25%-200% for those of us who use our regular PC for mining, or something? 

Preferably a configurable upper/lower limit

Thank you :)

(I can see where it happens, but pwsh knowledge is practically non-existant lol)

**Comment by RainbowMiner** [comment]
Oh! I see. Factor 2 is really much. Ok, I'll add something.

**Comment by RainbowMiner** [comment]
Here you go :)
Just set it to some higher values. It's +- to 100%. So if you set it to 30, the min. tolerance will start at 70% and the max. tolerance at 130%.

FYI, there is an auto-adapt build-in. If a miner fails due to "out of tolerance", the tolerance will be adjusted by steps of 10% (1 fail = +10%, 2 fails = +20%, 3+ fails = +30%).

**Comment by talentoscope** [comment]
Yet again, you surpass yourself sir!
Thank you buddy :)
