### ISSUE TITLE
[Question] OCprofiles custom per algo?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#1406]
[Question] OCprofiles custom per algo?

I overwrote the ocprofiles.config.txt for Ethash.  I want to put it back to default and set the OCprofile in the Algo section.

This says the default is "Profile2".
![DevicesConfigTXT](https://user-images.githubusercontent.com/801414/107893285-24da9800-6edf-11eb-81ff-254c78f2f62a.png)

And this is what I modified because I am currently only doing Ethash under "Profile2-GTX1070".  How does RBM pick between "Profile2" and "Profile2=GTX1070"
![OCprofilesTXT](https://user-images.githubusercontent.com/801414/107893306-476cb100-6edf-11eb-838c-12f1f866f6a1.png)

And this is the algorithms.config.txt
![AlgorithmsConfigTXT](https://user-images.githubusercontent.com/801414/107893357-90246a00-6edf-11eb-8751-595e9cc37a74.png)

Do I make a totally new Profile for the 1070 and Ethash?

**Comment by paulpoco** [comment]
I think I answered my own question.

Changed ocprofiles.config.txt to this
![Screenshot_13](https://user-images.githubusercontent.com/801414/107893644-43da2980-6ee1-11eb-9efa-68e753c2a39a.png)

And changed in Algo config
![Screenshot_14](https://user-images.githubusercontent.com/801414/107893663-594f5380-6ee1-11eb-823a-1905c73c6079.png)

One thing before I changed the algorithms.config.txt Ethash mining doesn't like the default Profile2-GTX1070 of +400 memory.

**Comment by paulpoco** [comment]
@RainbowMiner 

Ok small problem, changed the algorithms.config.txt Ethash OCprofile to "Profile2-GTX1070-Ethash" on the Server Rig with only 1070 cards and it somehow changed in the client 1660 Super Rig's algorithms.config.txt Ethash OCprofile to "Profile2-GTX1070-Ethash".  

I later changed on the client Rig with 1660 Super's algorithms.config.txt Ethash OCprofile to "Profile2-GTX1660SUPER-Ethash", is the Server going to change the clients Algo settings again?

**Comment by paulpoco** [comment]
Yup the Server is changing the algorithms.config.txt messing up my OC on the client by changing to use a 1070 profile on 1660 Super.

I am either doing it all wrong or there is a problem.

**Comment by RainbowMiner** [comment]
#### The mechanics of server/client config synchronization

Since every machine is individual, the clients will pull only the hardware independant config files from the server.

These are by default:
- config.txt (with some variables excluded, see below)
- coins.config.txt
- pools.config.txt
-  algorithms.config.txt
- scheduler.config.txt

Notes:
- these config files are defined and can be changed on the clients with parameter `"ServerConfigName": "config,coins,pools,algorithms,scheduler",`
- excluded variables in config.txt are by default `"ExcludeServerConfigVars": "APIAuth,APIPassword,APIPort,APIUser,CPUMiningAffinity,CPUMiningThreads,DeviceName,EnableServerConfig,ExcludeDeviceName,ExcludeServerConfigVars,GPUMiningAffinity,GroupName,LinuxDisplay,LinuxXAuthority,MSIApath,NVSMIpath,Proxy,RunMode,ServerConfigName,ServerName,ServerPassword,ServerPort,ServerUser,StartPaused,WorkerName,StaticCPUMinerPort,StaticGPUMinerPort"`

#### Hints, how to solve your problem

- the names of the ocprofiles are completely free to choose. There is no parsing or mapping to GPUs or algorithms.
- add one profile with name "Ethash" to every machine's ocprofiles.config.txt
- now add `"OCprofile": "Ethash",` to your server's algorithms.config.txt
- every client will pull the new algorithms.config.txt and use it's own "Ethash" profile.

.. at least, this is how I am doing it.

**Comment by paulpoco** [comment]
Thanks will explore it more

**Comment by paulpoco** [comment]
The info will help

**Comment by paulpoco** [comment]
@RainbowMiner how would I do this for a client with say 1660 Super and 3060 Ti?  How do I have two different Ethash profiles?   Proper naming so the Ethash in the Server will pickup correct OCprofiles per card?

**Comment by RainbowMiner** [comment]
Oh!! Sorry! This is not correct:
> the names of the ocprofiles are completely free to choose. There is no parsing or mapping to GPUs or algorithms

In fact, there is a parsing used for the ocprofiles.config.txt:
- add device group name via "-"
- add PCIe bus number via "-"
- add GPU name via "-"

RainbowMiner automatically adds o profiles for the device groups and the Profile1..5

In your case, add a ocprofile for every GPU group with the respective names
`"Ethash-RTX3060"` and `"Ethash-GTX1660SUPER"`

Using "Ethash" in algorithms.config.txt will now automatically pick the correct ocprofile for the GPUs

Addendum:
To address a GPU on PCIe address 05:00, you would use profile name `"Ethash-05:00"`. To address by name, use the syntax `"Ethash-GPU#01“`

**Comment by paulpoco** [comment]
Thanks.

If a RTX 3060Ti becomes available and not scalpers pricing I'll know what to do.
