### ISSUE TITLE
Q: Zerg auto-exchange

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#1438]
Hi!

What if I want to mine on 2miners with the auto-exchange feature? Is this a 2miners config thing or it can't be done with rbminer?

Thanks

**Comment by RainbowMiner** [comment]
I didn't know, that it now has an autoexchange. It will be added to our modules asap

**Comment by Djago** [comment]
Sorry, my bad, it wasn't 2miners, is Zergpool

**Comment by RainbowMiner** [comment]
Ah! Ok. I was really wondering.
So you want to define the autoexchange currency. That's easy, actually, we have two ways. 
- either change `"BTC": "$Wallet",` to your currency of choice in pools.config.txt / ZergPool . E.g `"ETH": "$ETH",` or cleartext `"ETH": "0xabc.....",`
- or, if you want to leave the BTC intact, or if you want to add multiple currencies, so that you can switch easily, in the future, just add the new currencies to pools.config.txt / ZergPool and tell RainbowMiner which one you want to use for autoexchange via the AECurrency parameter, e.g. `"AECurrency": "ETH",`

**Comment by Djago** [comment]
Great! Thanks!
