### ISSUE TITLE
MRR API's?

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#1441]
Can we use the same API key for all miners in a server/client setup? Or do we still need an API key for each rig?

**Comment by RainbowMiner** [comment]
In most of the times, it should be safe with one API key pair. It beomes tricky, if the server crashes or the network is disrupted. Since all calls to MRR are executed by the server, the timing should be clean. Each call to MRR needs a nonce number, that is greater than the nonce of the prior call. We use the machines timestamp in milliseconds. In the equal key case, it's the server's timestamp.

**Comment by Yamanipanuchi** [comment]
Okey, So if I understand correctly. In theory there should be not issues. But if you CAN setup separate API's it is more reliable or less susceptible to error's.

If that is correct, Good to know!

**Comment by RainbowMiner** [comment]
Yes, 100% correct.
