### ISSUE TITLE
RBM choosing Sparkpool over Nicehash despite lower payrate

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1445]
![image](https://user-images.githubusercontent.com/56473344/109151281-dd1b0280-7761-11eb-8303-c28343b79251.png)

This screenshot shows Nicehash clearly paying more than Sparkpool, yet Rainbowminer still chooses Sparkpool. Can you explain why this is?

**Comment by RainbowMiner** [comment]
It's most probably a mixture between accuracy, hash- and blockrate. Could you please show me the full rows of that table?

**Comment by samdave123** [comment]
![image](https://user-images.githubusercontent.com/56473344/109152286-320b4880-7763-11eb-9dac-a7a051798456.png)

**Comment by RainbowMiner** [comment]
Ok, now a screenshot of the console window would be good, so that we can see the miner accuracy.

**Comment by samdave123** [comment]
Sorry, I've had to go back into the office at work. I'll replicate these screenshots + the console window this evening.

**Comment by samdave123** [comment]
Ahhhhhh I got home, but now the circumstances have changed and Sparkpool is better paying. I'll wait until it happens again then upload the requested screenshots.

**Comment by samdave123** [comment]
![image](https://user-images.githubusercontent.com/56473344/109213264-4cb3e080-77a8-11eb-83a8-380ff6100637.png)

![image](https://user-images.githubusercontent.com/56473344/109213286-53daee80-77a8-11eb-9f19-4c4b3e16137c.png)

**Comment by samdave123** [comment]
I have a 10% penalty set on Sparkpool (I set a small penalty because I prefer being paid in BTC on Nicehash).

**Comment by samdave123** [comment]
Okay it's even more extreme now:

![image](https://user-images.githubusercontent.com/56473344/109220829-3f4f2400-77b1-11eb-98e1-0138f6d6eac2.png)

![image](https://user-images.githubusercontent.com/56473344/109220912-44ac6e80-77b1-11eb-9aed-7be5af0be438.png)

**Comment by acos0874** [comment]
Just to chime in here. I mostly mine on sparkpool. I really don't understand how stable price can be so much higher.... 
![image](https://user-images.githubusercontent.com/42582444/109224469-e1700b80-77b3-11eb-9201-10e506171cb3.png)

**Comment by acos0874** [comment]
I think I have happened upon something. So the sparkpool api states an income of "income":0.00584. I'm assume this is ETH/100MH/DAY since this incomeHashrate":"100000000". So converting this to BTC/GH/DAY is 0.0000185128 which looks about right in terms of rbm saying Price: 1.82814192e-12.

Now if I look at the hashrate of the miner doing 129MH/s with a revenue of 0.22291 this equates to 1.728e-6

Profit: 0.00019734115003063518
Profit_Bias: 0.00019734115003063518
Profit_Unbias: 0.00023361621437739953

So all of these figures seem roughly in the right ball park but it's so confusing to understand why rbm chooses one pool over the other and this is important so us to understand that we have our settings set correctly.

**Comment by RainbowMiner** [comment]
Ok, I will try to write a detailed explanation tomorrow. Actually, I do remember, that I have written down all the formulas in a different issue. I will try to find it.

To headstart today:
- most basically, you have to understand, that we compare the `StablePrice x (1 - MarginOfError x DecayFactor)`  of all pools against each other, except the Nicehash pool - here we always use the `Price` (it's 10 minutes moving average). This avoids removes heavy switching during times of price rollercoaster.
- The `StablePrice` is the 7 day moving average, so the stats will take time to adapt after huge price swings (like we had, the past weekend).
- The `DecayFactor` is a global, internal discrete function, that decreases the `MarginOfError x DecayFactor` over time, so that pools get a chance, even if their current MarginOfError is high.
- If you do not want to sit out the time until the moving average comes down or up after huge and quick price movement, just delete the pool's stat files in `.\Stats\Pools` - for SparkPool that would be all files, that match `SparkPool*.txt`

Maybe it would make sense to automatically switch the moving average time from 7 days to 3 days to 1 day for some time after huge BTC price drop/rise. I will think about that.

**Comment by samdave123** [comment]
Is it possible to just disable StablePrice?

**Comment by RainbowMiner** [comment]
Yes - there is one setting in config.txt. Set `"EnableFastSwitching": "1",`

**Comment by RainbowMiner** [comment]
Remark: the stats database automatically tracks all moving average timeframes. So you will not loose information and can switch between the different timeframes seamlessly

**Comment by samdave123** [comment]
> 
> 
> Yes - there is one setting in config.txt. Set `"EnableFastSwitching": "1",`
> 
> If you set it to "1", you can then set the moving average time of the `Price` per pool, with parameter `"StatAverage": "",` in pools.config.txt. Or you can set it globally in config.txt with parameter `"PoolStatAverage": "",` (see https://github.com/rainbowminer/RainbowMiner#change-a-pools-moving-average-stat-average for possible values)

Thanks, I'm going to do this, as I can actually understand what the profit-switcher is doing now.

**Comment by acos0874** [comment]
Would it be possible to have a switch to use the price instead of stable price for every pool? I'm not a big fan of using any kind of moving average since they lag behind the real data and I use only PPS pools, ideally instead of 

StablePrice x (1 - MarginOfError x DecayFactor)

It would just be 

Price x (1 - MarginOfError x DecayFactor)

For every pool. Also is the 10 minute moving average for nicehash part of a setting or hard coded? Ideally I'd like that to be removeable please.

**Comment by samdave123** [comment]
I enabled fastswitching, but my rig is switching a little more than I'd like. Ideally, I'd just like to disable stableprice without having to disable switching prevention.

**Comment by RainbowMiner** [comment]
@acos0874 the values described [here](https://github.com/rainbowminer/RainbowMiner#change-a-pools-moving-average-stat-average) do apply to Nicehash, even if `"EnableFastSwitching": "0",` (is not enabled).

**Comment by acos0874** [comment]
Ah ok, so I have mine manually set to live which should override it.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/109298904-2afc3d00-782c-11eb-9f6e-385137508669.png)
So is it possible that this part of the code could be optionally switched to live price or is it more complicated than that?

**Comment by RainbowMiner** [comment]
@samdave123 Yes, that is expected - it's called "FastSwitching". 

I will add another parameter to config.txt and pools.config.txt, so that we can select exactly, which price we will be using.

**Comment by samdave123** [comment]
> 
> 
> @samdave123 Yes, that is expected - it's called "FastSwitching".
> 
> I will add another parameter to config.txt and pools.config.txt, so that we can select exactly, which price we will be using.

Shouldn't there be some switching prevention even if stableprice is removed? Stuff like not switching when profits are marginally higher for short amounts of time? Does FastSwitching disable that too?

**Comment by RainbowMiner** [comment]
Yes, it's all there. With EnableFastSwitching enabled, you bypass all of these functions. So it is not suitable for your cause.
That is why I just implement another solution, that changes the method for the price/pool preselection

**Comment by acos0874** [comment]
> @samdave123 Yes, that is expected - it's called "FastSwitching".
> 
> I will add another parameter to config.txt and pools.config.txt, so that we can select exactly, which price we will be using.

That's awesome. Thank you!

**Comment by acos0874** [comment]
Can you also confirm please that pool switch hysteresis is working correctly? Last time I tried it with nicehash ethash and sparkpool ethash with a value of 40, there was still more switching than desirable.

**Comment by samdave123** [comment]
> 
> 
> Can you also confirm please that pool switch hysteresis is working correctly? Last time I tried it with nicehash ethash and sparkpool ethash with a value of 40, there was still more switching than desirable.

Just to check, you didn't enable FastSwitching which disabled hysteresis?

**Comment by acos0874** [comment]
No I have it disabled.

**Comment by RainbowMiner** [comment]
Done. I have chosen the hard way - but from now on, you can define the moving average times, not only for the Price, but for the StablePrice. Also, I have included a detailed description of the profit switcher beast into the Readme.md:
https://github.com/RainbowMiner/RainbowMiner#how-does-the-profit-switcher-work-and-how-can-i-change-its-behavior

**Comment by acos0874** [comment]
Brilliant. Thanks again!

**Comment by RainbowMiner** [comment]
A recommendation: I have made very good experience with a `"StatAverage": "Hour",` for Nicehash, even during times of huge market price swings.

**Comment by samdave123** [comment]
> 
> 
> Done. I have chosen the hard way - but from now on, you can define the moving average times, not only for the Price, but for the StablePrice. Also, I have included a detailed description of the profit switcher beast into the Readme.md:
> https://github.com/RainbowMiner/RainbowMiner#how-does-the-profit-switcher-work-and-how-can-i-change-its-behavior

wow I didn't realise it was so complicated, thank you for documenting it!

**Comment by acos0874** [comment]
`PFC is the price for comparison. It starts at either the pool's StablePrice or Price:
StablePrice: if EnableFastSwitching is "0" (=disabled) and either ForceStablePrice is "1" (=enabled) or the pool isn't internally marked as PaysLive (like Nicehash is)
live Price: all other cases (especially NiceHash)`

So with this bit, if I want to customise the PFC, should I use PoolStatAverageStable and set it to something like "live"?

**Comment by RainbowMiner** [comment]
> So with this bit, if I want to customise the PFC, should I use PoolStatAverageStable and set it to something like "live"?

Yes, exactly. If you go with the default setup:
- **PoolStatAverage** will determine the _PfC_ for NiceHash
- **PoolStatAverageStable** will determine the _PfC_ for all other pools, including the WhatToMine

**Comment by acos0874** [comment]
Ok so I'm set it with the following settings on all pools
DataWindow = current_estimate
PoolStatAverage = live
PoolStatAverageStable = live
Accuracy weight = 100
Switch prevention = 1

Max margin of error for nicehash = 5
Max margin of error for everything else = 100

My aim is to let the formula part " StablePrice x (1 - MarginOfError x DecayFactor) " be the only thing that decides profit switching and hence remove any use of moving averages. So anything on nicehash starts with a maximum 5% penalty in PfC and something like SONO on zergpool with an accuracy of 67% would have a 33% penalty and hence probably not ever be selected. I may tweak this parameters a bit to give zergpool a large penalty. 

For example I might increase the switch prevention to 2 and reduce the max margin of error on nicehash to 2.5 which would result in larger penalties for my volatile coins on zergpool. 

Please can you confirm I have understood this correctly and if you see any potential issues?

**Comment by acos0874** [comment]
Also I just noticed that for both nicehash and sparkpool ethash the stable price and price are giving identical values which seems like the changes have been effective.

However, there is one thing I have noticed when firing up my rigs. 

Nicehash is paying 1.716 with a margin of error of 0.17, but I have a max margin of error of 5 so reducing 1.716 by 5% is 1.63

Sparkpool is paying 1.88 with a margin of error of 0.22. I have max margin of error of 100 so reducing 1.88 by 22% gives 1.47

So in theory if I've understood correct the profit switcher should favour nicehash with the small penalty applied, however, it actually prefers sparkpool. So have I misunderstood how it work?
