### ISSUE TITLE
Asyncloader keeps crashing

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#1450]
I've noticed this a few times in recent days.

![image](https://user-images.githubusercontent.com/56473344/109384883-bd154b80-78e7-11eb-9de5-df53ac1985c3.png)

[debug_2021-02-27.zip](https://github.com/RainbowMiner/RainbowMiner/files/6054198/debug_2021-02-27.zip)

**Comment by RainbowMiner** [comment]
Since this problem becomes more and more acute, I suspect the Windows TCPIP stack getting overcrowded with network connections. Please try the following:

#### To set TcpTimedWaitDelay (TIME_WAIT):
1. start the regedit command
2. goto the "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TCPIP\Parameters" subkey
3. create a new REG_DWORD value named TcpTimedWaitDelay (or edit it, if it already exists).
4. set the value to 30
5. stop and restart your system

**Comment by samdave123** [comment]
Okay, I will test this now. If I don't update the issue within 10 days, then let's assume it's fixed.

**Comment by samdave123** [comment]
RBM crashed again, but no error message this time

**Comment by samdave123** [comment]
[debug_2021-02-27(1).zip](https://github.com/RainbowMiner/RainbowMiner/files/6055781/debug_2021-02-27.1.zip)

**Comment by samdave123** [comment]
Nicehash still says the rig is mining, but the console and localhost is unresponsive

**Comment by samdave123** [comment]
Is there any chance the recent update broke FastSwitching?

**Comment by RainbowMiner** [comment]
> Is there any chance the recent update broke FastSwitching?

Actually, no. The only change has been the new moving average adjust parameter.
