### ISSUE TITLE
Spike filter

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#1472]
Hi

Recently CN-XHV is doing a lots of spikes that makes the estimation rather unaccurate. Sometimes the calculated profit es 1.5ETH/day and when this peakes subsides it goes to the more rational 0.000728ETH/day. This kind of spikes lasts for something between 1 iteration to 4-5. Is there a way to filter this kind of "unrational" behaviour?
![image](https://user-images.githubusercontent.com/34612740/110257367-601b3480-7f7c-11eb-97dc-2693817d7a7e.png)

Regards

**Comment by RainbowMiner** [comment]
It is already filtered, that is why it goes away after 1-4 rounds. Actually, it should not change the stats, too. If it does, I will have to look into it.

**Comment by Djago** [comment]
But how is this filter working? When this happens the actual profit does not change until the profit gets lower again. Should this be de-listing the item in the list? or listing it with the lowered value?

**Comment by acos0874** [comment]
I've been using rainbowminer for 2 years and still don't understand it fully :D

**Comment by acos0874** [comment]
My understanding is it works like this... There are two prices used in a formula. 'Price' and 'StablePrice'.

The Price is effectively what is live and the StablePrice is a combination of a moving average and an accuracy figure. There is a third variable which is poolaccuracyweight and switch prevention, and this decide determines how each price values is considered. Here is an example of how these figures go into the profit switching.

Price = $3
StablePrice = $2
PoolAccuracy = 77%
SwitchPrevention = 3
StablePrice after accuracy penalty applied = $2 -  $2 x (1 - 0.77) x 3 = $0.62
PoolAccuracyWeight = 15%
Overall price for comparison = 15% x $0.62 + 85% x $3 = $2.64

This is my best guess about how the profit switcher works. You'll see that the StablePrice effectively penalises coins with low accuracy (aka volatile pricing), but you can still mine on them sometimes if the prices get too high. You can avoid switching to these overpriced coins by tweaking the above variables, but I've had mixed results with it since I'm not sure my understanding of it is fully correct.

**Comment by acos0874** [comment]
My theory is that if I use PoolAccuracyWeight as 100 and then switch prevent as 2, then anything with an accuracy of lesson that 50% will be penalised to 0.
