### ISSUE TITLE
RPlant Raptoreum not appearing

### ISSUE THREAD

**Issue by VoltaVX** [RainbowMiner/RainbowMiner#1541]
I want to try mining RTM on RPlant, however, when I select RPlant, I get a "No pools found" error.

[debug_2021-04-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/6298250/debug_2021-04-12.zip)

**Comment by RainbowMiner** [comment]
- It seems, there are only K1Pool and ZergPool on the "PoolName" list in config.txt. Put "RPlant" on the list.
- I would strongly recommend, that you set "Currency" to "BTC,USD" (or "BTC,RTM,USD"). But do not leave the BTC out.
- do not use "Wallet" in config.txt for other currency than BTC (only, if you know exactly, what you are doing). It's pretty important, since everything is being measured against BTC.
- add RTM to the RPlant pool in pools.config.txt:
```
    "RPlant": {
      "RTM": "yourraptoreumwallet",
      "RTM-Params": "",
...
```
.. alt. in case you have defined RTM in coins.config.txt:
```
    "RPlant": {
      "RTM": "$RTM",
      "RTM-Params": "",
...
```

**Comment by VoltaVX** [comment]
Thanks! Your suggestion worked
