### ISSUE TITLE
Mining rig show offline incorrectly.

### ISSUE THREAD

**Issue by yuanjs** [RainbowMiner/RainbowMiner#1618]
I have 4 mining rig at the same local network. All of them are running  normal. But one rig's local dashboard will show all the other three offline, if I switch to the other rig's dash board, only this one show offline, others are normal.
On the Monitoring Central, this rig also show offline, and other there are normal.

How can I find what happen there.
Thanks!

**Comment by RainbowMiner** [comment]
Please check the system time of that one rig - is it different to the system times of the other three?
- If yes: please adjust the time.
- If no: could you please upload a Debug file pulled from that one "special" rig and one Debug file from one of the three others? Open the local dashboards and find "Debug file" on the left hand side - click it - it will create a zip file with all sensitive data removed, so that you can safely upload it (them) here.

**Comment by yuanjs** [comment]
Thanks！
I think I found what happen. When I check the console of the offline rig, I found the console is hang up。After I click in side the console, It's response again. and then I check the monitoring central, everything is back to normal.

**Comment by RainbowMiner** [comment]
Perfekt :)
