### ISSUE TITLE
Profit predication are wrong

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#162]
I have been mining on RBM from more than month. But all profit estimates are wrong.
as you can see attached screenshot displays profit of 235 xvg per day. but, i never ever got more than 180 xvg per day. mining profit has already hit rock bottom and we don't even get the bottom price.
![image](https://user-images.githubusercontent.com/30832110/45735238-c3764800-bc04-11e8-9aba-d1be052075ce.png)

**Comment by RainbowMiner** [comment]
The live estimation is calculated from the values, the pools are delivering, thus depends on that. It looks like the pools are cutting their edge when doing the autoexchange. If I look at my mining results (which are in BTC), I see that my estimate is around 10 to 15% above the real revenue. Your's is quit a bit higher, so exchanging to XVG seems more expensive.

So we got some options:
- enter a Penalty of xx % to the pools (acts like a hidden pool fee)
- monitor the real income against the profit calculation and adjust accordingly
- compare pools, to see, which pool pays best, and which pays worst

The first is an easy fix, as a penalty can be entered directly into the pools.config.txt. 
The second is a more sophisticated way. I will think about it, since I currently work on the tracking of payments from the pools, this may work.

In the past, Blazepool and Nicehash have been paying most accurate. Do you have a feeling for the pools, you are using?

**Comment by RainbowMiner** [comment]
Oh, I got another option, which I remember have been using some months ago. This got me the most accurate estimates: I changed the datawindow for all pools to "minimum-3", except for Nicehash. It could be a good start for adjusting the estimates. Another option would be, if you use "actual_last24h" as datawindow and see, how far you get with that. 
You see, it all depends heavily on the honesty of the pools and our fine tuning of the system, using DataWindow and Penalty as the screws to turn.

**Comment by rinkal26783** [comment]
I was looking for way to improve my profit. 
- Setting up penalty is not my favorite option. As i can't be sure about same penalty would apply while mining different coins.
- Monitoring real income is very good option. It would help to know real income. In this feature you should show cleared balance. So, its accurate.
- My opinion about pools.
Zergpool - They shows more profit in immature and exchance balance. but after exchange coins are cleared. they cut your profit to 10-15%. Yesterday my profit was going up for 8 hours but suddenly my income got 10% down and i had to mine 6 hours to get back at same profit. It means I mined and got nothing for 6 hours.
-Zpool- They always pay less compare to other pools. but, don't do cheating like zergpool
-blazepool- they have few miners. so we must mine only selected algo with lots of miners.
-blockmaster- they pays more compare to other pools, but still i get 25% less out of estimated profit.

**Comment by rinkal26783** [comment]
I prefer to mine with few algos which consume low energy. lyra2z,yescrypt,yescryptr16,allium,phi2
and add 1 more algo x16s which consume more energy but its more profitable and accurate. It's quick to find new blocks with all x16s coins. So, even with few miners we can find many blocks every hour.

my data windows is current estimations. because with my selected list of algos, I must give more frequent switch to diff algos.

I also noticed RBM switch less compare to nemosminer. 
I use to extract electricity price from profit so it gives fare chance to mine other algos. but still RBM switch less frequently compare to nemos

**Comment by RainbowMiner** [comment]
I implemented a switching prevention into RainbowMiner. That lowers the switching frequency. It helps a lot, if you mine slow algorithm, like ethash. If you want to increase switching, you may lower the SwitchingPrevention in config.txt (it defaults to 2).
It is a floating point number, so you can lower the value in fractions, downto 0 (=no switching prevention at all).
