### ISSUE TITLE
Ubuntu 20.04 LTS ocdaemon service problem

### ISSUE THREAD

**Issue by yuanjs** [RainbowMiner/RainbowMiner#1626]
I found the error message below. and RBW can not set the oc setting. I can set all the oc setting manual.

/etc/systemd/system/ocdaemon.service:20: Failed to parse output specifier, ignoring: /opt/rainbowminer/ocdcmd/ocdaemon.error.log

**Comment by RainbowMiner** [comment]
Thank you for reporting this - I'll have a look.

**Comment by RainbowMiner** [comment]
Ok, I have proposed a fix. After the next release - or after having downloaded and extracted the newest master.zip into your RainbowMiner folder (or simply download the file [ocdaemon.service](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/65cd451ad9db460a175884a4443ddead169d611b/IncludesLinux/conf/ocdaemon.service) into the folder `./IncludesLinux/conf`) you will have to re-run `./install.sh`. This should overwrite the `/etc/systemd/system/ocdaemon.service` file with the newest version. 

Shortcut:
edit `/etc/systemd/system/ocdaemon.service` as root (e.g. `sudo vi /etc/systemd/system/ocdaemon.service`) and change line 22, so that it looks like that: `StandardError=null`

**Comment by yuanjs** [comment]
Cool！ It works now.

Is it possible do add a fix fan speed option in the ocprofile ?

Thanks!
