### ISSUE TITLE
RavenMiner SSL connection

### ISSUE THREAD

**Issue by orbital253** [RainbowMiner/RainbowMiner#1643]
I'm having issues connecting to RavenMiner with ssl connection. Disabling non-ssl connection in "All Pools" also disables ssl connections, so the whole pool is disabled. i have manually tested that connecting to pool with ssl seems more stable whereas simple tcp connections tend to disconnect very often.

**Comment by RainbowMiner** [comment]
Thank you for reporting this! It turned out, that the API urls needed an update. I have just updated the `.\Pools\Ravenminer.ps1` pool module. To update, either download the new version of that file (https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Pools/Ravenminer.ps1 - right-click and Save as) into your `.\Pools` folder, or wait for the next release.

Then, everything works as expected:
- add "Ravenminer" to "PoolName" in config.txt
- edit pools.config.txt, find "Ravenminer" and set "SSL" to "1" for this pool and you will be mining away with SSL:
```
  "Ravenminer": {
    "RVN": "$RVN",
    "DataWindow": "",
    "Worker": "$WorkerName",
    "Penalty": 0,
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "ExcludeCoin": "",
    "CoinName": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "0",
    "StatAverage": "",
    "MinerName": "",
    "ExcludeMinerName": "",
    "EnablePostBlockMining": "0",
    "CoinSymbolPBM": "",
    "MaxMarginOfError": "100",
    "SwitchingHysteresis": "",
    "MaxAllowedLuck": "",
    "MaxTimeSinceLastBlock": "",
    "Region": "",
    "StatAverageStable": "",
    "SSL": "1"
  },
```

**Comment by AnthonyBe** [comment]
Since updating from RM 4.7.2.6 to 4.7.2.8 I've now lost Ravenminer from my pool balances altogether.
I've tried with both SSL on and off in the Ravenminer pools.config.txt but same result.

[debug_2021-07-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/6780432/debug_2021-07-08.zip)

**Comment by AnthonyBe** [comment]
nvm. It's reappeared!

**Comment by RainbowMiner** [comment]
Thanks for reporting back.
