### ISSUE TITLE
Waiting for Internet Connection 

### ISSUE THREAD

**Issue by mitchngwen** [RainbowMiner/RainbowMiner#1712]
Setup and configuration is done and when I run ./start.sh. I get:
WARNING: Waiting 30s for internet connection. Press [X] to exit RainbowMiner

It never gets past this.

**Comment by RainbowMiner** [comment]
There is a build-in function, that tests for internet connection. It seems to fail to find an internet connection, for some reason.
- First, do you have internet connected? (Sorry, it's a dumb question, but it's just to be sure)
- Do you have any proxy or router, that could block that connection test attempts?
- Are there any errors or warnings (with font color red or yellow)?
- Which Linux distro have you installed?

Could you please create and upload a Debug file? While RainbowMiner is running (./start.sh), just open http://localhost:4000 (or use your rig's ip address, http://<ip-address>:4000), then click "Debug file" on the left hand side.

If everything fails, I can supply you with a quick fix. Later, in the next release, I will add a switch in the config.txt, so that you can simply disable the Internet-test.

**Comment by kriswebdev** [comment]
On Linux (Ubuntu 20.04):

After troubleshooting, the cause is indeed a known issue of PowerShell for Linux: #https://github.com/PowerShell/PowerShell/issues/14678

```
PS> Test-Connection -ComputerName www.google.com
Test-Connection: Testing connection to computer 'www.google.com' failed: An exception occurred during a Ping request.
Test-Connection: Testing connection to computer 'www.google.com' failed: An exception occurred during a Ping request.
Test-Connection: Testing connection to computer 'www.google.com' failed: An exception occurred during a Ping request.
Test-Connection: Testing connection to computer 'www.google.com' failed: An exception occurred during a Ping request.
```

The existing recommendations to overcome this issue are actually too dangerous, i.e. running PowerShell as root (or setuid, which is the same). Developing a workaround using `System.Net.NetworkInformation.Ping` instead of `Test-Connection` is possible however annoying, you'll have to manage exceptions. If you want to go this way, see:
https://social.technet.microsoft.com/Forums/windowsserver/en-US/901c01a0-4c12-41fc-b6b0-2da4321de94e/why-am-i-getting-exceptions-from-my-pings?forum=winserverpowershell

Otherwise, the simplest way to workaround this issue would be to add a config setting to skip this check, as you suggested; and a recommendation to use it in the warning message.

To end users: Until this is fixed, you can edit `RainbowMiner/Modules/Core.psm1` to replace `$Internet_ok = Test-Internet -CheckDomains $Session.Config.WebsitesForOnlineCheck` by `$Internet_ok = $true`. You'll have to do this after every auto-update of the app.

**Comment by RainbowMiner** [comment]
Good find! Thank you very much for the troubleshooting. I'll upload a fix asap.

**Comment by RainbowMiner** [comment]
Ok, I have temporarily disabled the internet-check for Linux, if RainbowMiner is not running as root. Just until I find a better solution for Linux.

**Comment by RainbowMiner** [comment]
Final fix implemented - now we just use curl. If it isn't installed on your system, the test will be disabled.
