### ISSUE TITLE
GPU Numbering

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1765]
I'm having an issue where using remote desktop is creating an additional intel device which messes up the GPU numbering and causes RBM to redo benchmarks. I remember this coming up before but I can't find the issue on Github. Is there a setting I need to change?

**Comment by RainbowMiner** [comment]
It has to do with the OpenCL platform sorting. RainbowMiner keeps the initial sorting in file `.\Data\openclplatforms.json`. It looks like that:
```
[
  "NVIDIA",
  "INTEL"
]
```

... if, at any time, that platform sorting changes in your system, RainbowMiner will resort the GPUs automatically, so that the GPU#00, GPU#01 etc. will stay the same. You can manually resort the values in that file to change the GPU count. First entry - gpus will be counted, starting from 0. Second entry - gpus will be counted, starting from number of first entry-gpus, and so on.

BUT

This relies on the fact, that the number of OpenCL platforms stays the same. As soon, as the number of platforms changes (e.g. if there is no more INTEL, at some time, eventually due to the fact, that there is no active remote desktop connection anymore), that file will be rewritten. Is this the case, with your system?

**Comment by RainbowMiner** [comment]
I could add a parameter "OpenCLPlatformSorting" to config.txt, so that you can manually define the sorting. This parameter would have priority over the automatically created openclplatforms.json file.

In fact, that would be very smart. I'll add this.

**Comment by acos0874** [comment]
![image](https://user-images.githubusercontent.com/42582444/136659440-53989fcf-156f-4622-b98e-e573d418f0fe.png)
Ok it did it this time.

**Comment by ZZCoder1** [comment]
@RainbowMiner  My actual GPU count is 5.
