### ISSUE TITLE
Custom wallet address in ZergPool conf doesn't work

### ISSUE THREAD

**Issue by thepagan** [RainbowMiner/RainbowMiner#1813]
When adjusting the Pool config for ZergPool to set a static custom wallet address and coin type, the coin type (c=) gets passed to the client, but the custom address (User = "ADDRESS_HERE" instead of User = $Wallets.$Pool_Currency) does not. It uses the encoded BTC wallet, even with custom address saved in file.

Manually setting the primary wallet address to custom in main Config/config passes the manual setting.

**Comment by xiaolin1579** [comment]
Config in file "pools.config.txt"
![image](https://user-images.githubusercontent.com/10980342/141293980-49d1f759-172f-44f7-b206-024d34a1e6bd.png)

**Comment by RainbowMiner** [comment]
Since ZergPool is an autoexchange pool, one has to define, which wallet it has to use for that purpose. It has it's build-in prio, starting with the BTC default wallet.

So, two possible solutions:
- either remove the "Wallet" parameter and replace it with your coin's (e.g. `"DOGE": "$DOGE",` or `"DOGE": "<yourwalletaddress>",`)
- or add your coin's wallet (e.g. `"DOGE": "$DOGE",` or `"DOGE": "<yourwalletaddress>",`) and **set the parameter AECurrency to your auto-exchange coin**: `"AECurrency": "DOGE",`
