### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by MasterDoge1** [RainbowMiner/RainbowMiner#1832]
![image](https://user-images.githubusercontent.com/94486035/142058002-4467eaf8-a233-4a2f-bf7c-5422a860e5a2.png)
I am unable to connect using Rainbowminer. I can connect with other miners such as Trex and Miniz. I believe the college I am at is doing some kind of port blocking. I believe this is the case because some other miners will not connect while some do.
[RainbowMiner_2021-11-16.txt](https://github.com/RainbowMiner/RainbowMiner/files/7550143/RainbowMiner_2021-11-16.txt)

**Comment by RainbowMiner** [comment]
Ok, very probably, there is some kind of blocking. We could try to disable the test internet function, just to try if it's simply the pinging of this function. 
Please download the following zip file. There is only one file (Core.psm1) in this archive - extract it into the RainbowMiner `.\Modules` folder and overwrite the default one. Then try again. The internet check is disabled in this module.
[Core.zip](https://github.com/RainbowMiner/RainbowMiner/files/7550474/Core.zip)

Please let me know, if it worked out for you. If yes, I'll add an option for you, so that you can constantly disable the internet checker

**Comment by MasterDoge1** [comment]
Thanks a bunch. By using this module, the downloads for the miner started
so I believe issue FIXED :DDDDDDDDDDDDD

**Comment by RainbowMiner** [comment]
Question:
- are you using a proxy?
- could you please be so kind and create and upload a Debug file? Just open http://localhost:4000 and click "Debug file". A zip file will be created with all sensitive information x-ed out.

I just want to make sure, that my next release doesn't break your setup.

**Comment by MasterDoge1** [comment]
Local host works,but some miners are not working. The one I am interested
in is SRBminer because friends are mentioning that its the most profitable
atm

**Comment by MasterDoge1** [comment]
suprminer with Heavy hash*

**Comment by RainbowMiner** [comment]
Ok, I'll need that Debug file, so that I can check this:
- could you please be so kind and create and upload a Debug file? Just open http://localhost:4000 and click "Debug file". A zip file will be created with all sensitive information x-ed out.

**Comment by MasterDoge1** [comment]
Sorry about that. Could've sworn I sent it

**Comment by MasterDoge1** [comment]
[debug_2021-11-17.zip](https://github.com/RainbowMiner/RainbowMiner/files/7559191/debug_2021-11-17.zip)

**Comment by RainbowMiner** [comment]
SrbminerMulti is a AMD&CPU miner, so it will mine Heavyhash on your CPU, only. But there is a second miner, you should look out for: Suprminer. That one exclusively mines Heavyhash on single Nvidia GPUs. It will never show up in a combo of GPUs. So, goto http://localhost:4000/activeminers.html or http://localhost:4000/miners.html or http://localhost:4000/activeminers.html and select the Suprminer in the Miner-dropdown to see, how this miner has benchmarked on your GPUs. If it is nowhere to be found, goto http://localhost:4000/minerstats.html and check, if it's failed to benchmark.

Regarding your connection issues, I have (am currently) reworking the Test-Internet function, so that it can handle your ping-blocker.
