### ISSUE TITLE
[HEADSUP] Gminer contest started, automatic participation

### ISSUE THREAD

**Issue by RainbowMiner** [RainbowMiner/RainbowMiner#1874]
Gminer runs a contest from 12/8 to 12/29/2021 - if you want to participate, simply add an ETH wallet address to coins.config.txt and RainbowMiner will automatically add it to the miner. Until or unless you add your own wallet, RainbowMiner will add it's donation wallet to the gminer's command line.

Read the contest-rules here: https://github.com/RainbowMiner/miner-binaries/releases/tag/v2.74-gminer

**Comment by paulpoco** [comment]
@RainbowMiner Does this need to be in the command line for the contest?
15. use --user_id option to get unique id of rig

**Comment by paulpoco** [comment]
GMiner v2.74

+ contest, prizes: 25 x 0.2 ETH
+ improved stability for LHR mining
+ improved LHR auto-tune
+ now --proxy option using for user and dev fee connections
+ added option to disable non ssl dev fee connections (--dev_fee_ssl 0)
+ fixed --tfan on some RTX30xx cards

contest rules
1. you need to use gminer from version 2.73 or higher
2. for participation in contest, you need to run miner with "--contest_wallet ETH_WALLET" parameter, accordingly specifying a valid Eth wallet in the parameter (for example: --contest_wallet 0x5218597d48333d4a70cce91e810007b37e2937b5)
3. condition for participation in contest is use of gminer on any algorithm and with any hashrate with --contest_wallet parameter for at least 168 hours
4. each rig participating in contest has same weight regardless of hashrate (from laptop to rig with 20 cards)
5. miner notifies contest server every hour of continuous work, server remembers number of hours worked and wallet for contest specified in --contest_wallet parameter
6. user ID is set of hardware IDs, there is no point in running multiple copies of the miner in parallel on same rig, this does not increase chances of winning
7. miner running on multiple rigs, even with same Eth wallet specified in the --contest_wallet parameter, increases chances of winning in proportion to number of rigs
8. server stores number of hours worked, miner can be restarted without losing accumulated time
9. in process of working with --contest_wallet parameter, current progress in fulfilling conditions of contest is displayed under statistics table (for example, Contest: 7/168)
10. in order to become participant in contest and fulfill the necessary conditions, period of time equal to a week is given
11. at end of contest, data about users (serial number, unique identifier, Eth wallet) who have fulfilled all conditions are uploaded to numbered list and placed in public access
12. winners are selected from public list of participants using online roulette in live broadcast
13. each of winners is sent certain amount of coins to Eth wallet specified in the --contest_wallet parameter
14. each participant can win unlimited number of times
15. use --user_id option to get unique id of rig
16. list of participants is periodically published in "Gminer Talk" group ( https://t.me/gminer_talk )

prizes: 25 x 0.2 ETH
constest start date: 12/08/2021
constest end date: 12/29/2021

**Comment by RainbowMiner** [comment]
> 15. use --user_id option to get unique id of rig

No - that is just for you to find out the unique ID of the rig
