### ISSUE TITLE
Switching on the "," names option in Common options gives unrecognisable names

### ISSUE THREAD

**Issue by Vivraan** [RainbowMiner/RainbowMiner#1888]
The following are the names I get when using this option:
`Equihash,Equihash16x5,Equihash21x9,Equihash24x5,Equihash24x7,EquihashR25x4,EquihashR25x5,EquihashR25x5x3,EquihashVds`
Aren't these supposed to look like `equihash125,4` and so on?

In the miner config options, rbminer can tell that `equihash125,4` is the same as `EquihashR25x4` , but not when configuring algorithms.

**Comment by RainbowMiner** [comment]
Thank you for reporting this - I will fix it. In the meantime, just leave out the ",4". RainbowMiner will detect "equihash125" correctly as equihash125,4 aka EquihashR25x4

**Comment by RainbowMiner** [comment]
Ah, sorry, I misunderstood. These names are totally ok. Some history to that:
Internally, RainbowMiner uses those names: https://github.com/RainbowMiner/RainbowMiner#special-notes-for-equihash
Since it turned out, that many users got confused with that nomenclature, I later decided to add a translation table (algorithm mapping table), so that the abbreviated names will be shown at the frontend. The config.txt parameter "EnableAlgorithmMapping" switches this mapping on "1" and off "0" (it defaults to "1").
But inside the config files, we use these names with "x" for the Equihash algorithms. Also, these "x"-names will appear in the setup functions, too.
I will think about a reverse mapping for the setup, so that you will always see the abbrev. names. Except if you edit the config files directly.

**Comment by Vivraan** [comment]
> Ah, sorry, I misunderstood. These names are totally ok. Some history to that: Internally, RainbowMiner uses those names: https://github.com/RainbowMiner/RainbowMiner#special-notes-for-equihash Since it turned out, that many users got confused with that nomenclature, I later decided to add a translation table (algorithm mapping table), so that the abbreviated names will be shown at the frontend. The config.txt parameter "EnableAlgorithmMapping" switches this mapping on "1" and off "0" (it defaults to "1"). But inside the config files, we use these names with "x" for the Equihash algorithms. Also, these "x"-names will appear in the setup functions, too. I will think about a reverse mapping for the setup, so that you will always see the abbrev. names. Except if you edit the config files directly.

Ah, thanks for this document – explains the numbering! TIL.
Commonly, of course, I've been accustomed to seeing the `(n, k)` descriptors so the fact that we could express it by hardness or `(n/(k+1), k)` did not occur to me! Plus the addition of the R parameter makes perfect sense since I kept reading about it from multiple sources too!

Thankfully if I do have to set up an algorithm I can't name, I can always try the name of the coin I want to mine and it should get the desired algorithm accordingly (provided the coin doesn't sport multiple algorithm setups!).

**Comment by Vivraan** [comment]
I have a few more questions which might be best answered through Issues – unfortunately I don't find a lot of traction on Discord.
