### ISSUE TITLE
Worker individual profit (Same wallet, differrent workername)

### ISSUE THREAD

**Issue by TheeeX** [RainbowMiner/RainbowMiner#1954]
After our discussion,

> No, that is not possible directly, currently. What you can do, is to download the current "Activity" CSV and import it into a spreadsheet handler like Excel, for example. It's a bit uneasy to interpret, but it reflects the worker's profits.

_Originally posted by @RainbowMiner in https://github.com/RainbowMiner/RainbowMiner/issues/1939#issuecomment-1014577564_

I imported `Activity_20xx-xx-xx.txt` in Excel after running a worker for few hours, I have a few observation where I want your help.

1. What is difference between `Profit` and `TotalProfit` in Activity data. How do I calculate total worker profit in a session. Also what is the use of `MaxActivityDays`, `Ratio` in profit.
2. Profit in Activity file is not always increasing, Is this behavior right?
  
{"ActiveStart":"2022-01-19 06:38:38" | ActiveLast:"2022-01-19 06:44:46" | Name:"CpuminerJayddee" | Device:["CPU"] | Algorithm:["Lyra2z330"] | Pool:["ZergPool"] | Speed:[553.9061363636364] | Profit:3.1586128155663306E-06
-- | -- | -- | -- | -- | -- | -- | --
{"ActiveStart":"2022-01-19 06:38:38" | ActiveLast:"2022-01-19 06:45:51" | Name:"CpuminerJayddee" | Device:["CPU"] | Algorithm:["Lyra2z330"] | Pool:["ZergPool"] | Speed:[553.7722727272727] | Profit:3.113481022935604E-06
{"ActiveStart":"2022-01-19 06:38:38" | ActiveLast:"2022-01-19 06:47:08" | Name:"CpuminerJayddee" | Device:["CPU"] | Algorithm:["Lyra2z330"] | Pool:["ZergPool"] | Speed:[555.1297727272726] | Profit:3.064534140391249E-06
{"ActiveStart":"2022-01-19 06:38:38" | ActiveLast:"2022-01-19 06:48:14" | Name:"CpuminerJayddee" | Device:["CPU"] | Algorithm:["Lyra2z330"] | Pool:["ZergPool"] | Speed:[546.7648888888891] | Profit:3.0299123804585057E-06
{"ActiveStart":"2022-01-19 06:48:50" | ActiveLast:"2022-01-19 06:49:19" | Name:"CpuminerVerium" | Device:["CPU"] | Algorithm:["ScryptN2"] | Pool:["ZergPool"] | Speed:[0.0] | Profit:2.980833917198409E-06
{"ActiveStart":"2022-01-19 06:48:50" | ActiveLast:"2022-01-19 06:50:28" | Name:"CpuminerVerium" | Device:["CPU"] | Algorithm:["ScryptN2"] | Pool:["ZergPool"] | Speed:[24.62] | Profit:2.98231887506585E-06
{"ActiveStart":"2022-01-19 06:48:50" | ActiveLast:"2022-01-19 06:51:31" | Name:"CpuminerVerium" | Device:["CPU"] | Algorithm:["ScryptN2"] | Pool:["ZergPool"] | Speed:[24.35499999999998] | Profit:2.986453665672836E-06
{"ActiveStart":"2022-01-19 06:48:50" | ActiveLast:"2022-01-19 06:52:37" | Name:"CpuminerVerium" | Device:["CPU"] | Algorithm:["ScryptN2"] | Pool:["ZergPool"] | Speed:[24.246000000000024] | Profit:2.9902654250323683E-06
{"ActiveStart":"2022-01-19 06:48:50" | ActiveLast:"2022-01-19 06:53:41" | Name:"CpuminerVerium" | Device:["CPU"] | Algorithm:["ScryptN2"] | Pool:["ZergPool"] | Speed:[24.604333333333354] | Profit:2.9943882923868564E-06

3. How to interpret the data updated by `Set-Total` in _Stats\Totals_ directory. Can you explain a little bit about `ProfitApi`, `Penalty`.
4.  In Function `Write-ActivityLog`, do we calculate profit in the activity to calculate avg profit?

**Comment by RainbowMiner** [comment]
First of all: I'ld recommend to use the "Download as CSV" button on the Activity-page.
![image](https://user-images.githubusercontent.com/39437538/151565416-18c24f3d-78be-432a-af45-048a73d103a0.png)

.. this will create a file, that can be opened with Excel.
The activity-file is sort of a protocol log, that tracks continuous times of mining on a device.

- What is difference between Profit and TotalProfit in Activity data.

  `TotalProfit = Profit - TotalPowerDraw x PowerPrice`

  PowerPrice in BTC per Wh
  TotalPowerDraw in Wh
  Profit, TotalProfit in BTC

- How do I calculate total worker profit in a session.

  Sum up all TotalProfit where ActiveStart is greater or equal your sessionstart.
 
- Also what is the use of MaxActivityDays
  
  RainbowMiner will keep mining sessions for the given days, only (defaults to 2 days). Older activity data will be deleted. 

- Ratio in profit.

  Which ratio do you mean by that?

- Profit in Activity file is not always increasing, Is this behavior right?

  Yes, because it's the profit of one continuous mining period. If the profit-switcher changes to another algorithm, the finalized data of the current session will be written to the activity log and data collection for the next one will be started.
