### ISSUE TITLE
Discord Trading Channel

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#1964]
Please can you add one? I often have ideas I'd like to share and I like to hear other people's views but I'm conscious it might be annoying for people if it goes in the General channel.

**Comment by RainbowMiner** [comment]
Ok, it's #trading

**Comment by dakingwow** [comment]
What discord of rainbowminer?

**Comment by RainbowMiner** [comment]
> What discord of rainbowminer?

Here is an invite to out discord channel: https://discord.gg/znzQpJWWQH

**Comment by dakingwow** [comment]
How to remove offline workers on rainbowminer?

**Comment by RainbowMiner** [comment]
> How to remove offline workers on rainbowminer?

The offline workers on Https://rbminer.net will be deleted automatically after 48 hours. If you need a more speedy solution, please let me know. I could add a "Remove offline Workers" button.

**Comment by dakingwow** [comment]
Is possible remove on terminal (rainbowminer folder)?

**Comment by RainbowMiner** [comment]
> Is possible remove on terminal (rainbowminer folder)?

Could you please upload a screenshot from where you want it removed?
I am not sure, where you want it removed: do you want something like a commandline util (or hotkey in console) to trigger a removal of all offline workers on rbminer.net? Or else?

**Comment by dakingwow** [comment]
Yes, need command line for remove offline workers before 48hrs

**Comment by dakingwow** [comment]
Is possible?

**Comment by RainbowMiner** [comment]
> Is possible?

Yes, I will add something.

**Comment by RainbowMiner** [comment]
@dakingwow added.

- add button "Delete Offline Workers" to Dashboard page on http://localhost:4000 (corresponds to new button on rbminer.net). This will send a reset signal to rbminer.net, so that all workers will be removed that are marked as "Offline"
- add ResetWorkers.bat/resetworkers.sh commandline scripts, that will send a reset signal to rbminer.net, so that all workers will be removed that are marked as "Offline"

There are multiple files changed, so either wait for the next release or just download the changed/new files (right-click + save-as) into your RainbowMiner folder:
[Scripts/API.ps1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Scripts/API.ps1)
[web/index.html](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/web/index.html)
[ResetWorkers.bat](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/ResetWorkers.bat)
[resetworkers.sh](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/resetworkers.sh)
[Scripts/ResetWorkers.ps1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Scripts/ResetWorkers.ps1)
