### ISSUE TITLE
RainbowMiner keeps installing OpenHardwareMonitor

### ISSUE THREAD

**Issue by ZZCoder1** [RainbowMiner/RainbowMiner#1967]
Why is RainbowMiner installing this every few minutes? How can I stop it? It should not be necessary and it floods the system event logs.

A service was installed in the system.

Service Name:  WinRing0_1_2_0
Service File Name:  \RainbowMinerV4.7.2.3_win\Includes\getcpu\OpenHardwareMonitorLib.sys
Service Type:  kernel mode driver
Service Start Type:  demand start
Service Account:

**Comment by RainbowMiner** [comment]
Another update: even though the LibreHardwareMonitorLib is more up-todate, it still uninstalls the ring driver with the call to the Close() method. For that reason, I have added an option to GetCPU.exe, so that it can be started as permanent background job at the start of RainbowMiner thus effectively avoiding the Close() method. Now the log entries are finally gone.
