### ISSUE TITLE
Gminer ETH + TON not enabled?

### ISSUE THREAD

**Issue by coolbreeze21** [RainbowMiner/RainbowMiner#1976]
Gminer added ETH + TON dual mining with v2.79 (RBM v.4.8.1.4).  Gminer has now been updated to v2.80 in RBM 4.8.1.5.  But I haven’t seen RBM benchmark or enable Gminer ETH + TON during either update.  Am I missing something?

**Comment by RainbowMiner** [comment]
You are right - it's now theoretically dual mining enabled, but it turned out, that the v2.79 was pretty incompatible with the current pools. Also, it has been causing some trouble, so I currently keep the dual mining feature disabled in the module.
I haven't checked, if the v2.80 is now more compatible, because the issues still keep coming in at https://github.com/develsoftware/GMinerRelease/issues - as soon as I am sure, that the dual mining is safe, I'll enable it.

**Comment by coolbreeze21** [comment]
I thought it might by something like that, which is why I waited one version update before saying anything.  The Gminer 2.80 release notes say "fixed compatibility with major ethash pools in dual mining mode (connection closed error)", so it may be worth another look/test.

**Comment by RainbowMiner** [comment]
Ok, I'll test it now.

**Comment by RainbowMiner** [comment]
Nope. Still no connect to our four TON pools: https://github.com/develsoftware/GMinerRelease/issues/657

**Comment by coolbreeze21** [comment]
OK, thanks for trying!
