### ISSUE TITLE
Possibility to change the benchmark time?

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#20]
Is there any parameter or somewhere in the code I can change the time of each benchmark. It is taking ages and I would just like to run 3-4 minutes on each.

**Comment by RainbowMiner** [comment]
Most miners will take no longer than 1-2 minutes to benchmark. But: RainbowMiner starts with the watchdog sensitive algorithms, like X16r (5-10 minutes), HEX (3-4 minutes) and PHI (2-3 minutes). Those run with an increased time interval, temporarily. This is by design, since these algorithm deviate a lot over time.
If you want, I can provide an extra config parameters, so that you can disable the extended intervals.

RBM

**Comment by ebojali** [comment]
Ah ok, Now I understand, Keep it as is since I am ok with that. So the msi profile will not add any extra overclocking on the profile I use now or will it set everything to 0 i I use profile 1? This is confusing me

**Comment by RainbowMiner** [comment]
If you do want to stay with MSI Afterburner profile for every miner, you should disable the profile switching in RainbowMiner. In your config.txt, set  "MSIAprofile" to 0 ( "MSIAprofile": 0) and the profiles will not be switched.

So or so: RainbowMiner will never increase overclocking values. It will only switch through the profiles one to five, that you have defined yourself in MSI Afterburner. For normal operation, it will use the profile, you have provided in the config.txt, at field "MSIAprofile".

I have implemented the profile switching, because some algorithm operate faster and more stable, if overclocking is adjusted for them. For example: ClaymoreEthash dual miners are a bit sensitive, when the memory clock is too high, or X16r and X16s do not need memory overclocking at all, they even run faster without.

If one of the following algorithm will be mined, RainbowMIner will switch to another MSI Afterburner profile:
- ClaymoreEthash-Keccak & NeoScript will use Profile 3
- Lyra2re2, Lyra2z, X16r, X16s will use Profile 4
- ClaymoreEthash-Blacke2s, ClaymoreEthash-Pascal will use Profile 5

These are the profiles, I defined in MSI Afterburner for my GTX1070 rigs:
- Profile 1: no overclocking (+0/+0)
- Profile 2: max. core / max. memory oc (+100/+400), recm. as default
- Profile 3: max. core / half memory oc (+100/+200), recm. for claymore ethash-keccak, neoscrypt
- Profile 4: max. core / no memory oc (+100/0), recm. for lyra2re2, lyra2z, x16r, x16s
- Profile 5: max. core / reduced memory oc (+100/+350), recm. for claymore ethash-blake2s, claymore ethash-pascal

Of course those values are good for GTX1070, only. If you have other cards, other values will be better.
