### ISSUE TITLE
Review alt coin conversion to BTC

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#204]
Please review it may be something not right. Kreds is nowhere near the rate to BTC/USD shown in the picture
![image](https://user-images.githubusercontent.com/41829368/46685432-b967b980-cbb2-11e8-917d-35853f2fada7.png)

**Comment by RainbowMiner** [comment]
I will check with the values.

**Comment by hernandn01** [comment]
for reference is about 10 times as high
![image](https://user-images.githubusercontent.com/41829368/46694841-1a02f080-cbcb-11e8-9915-862833b0eff6.png)

**Comment by RainbowMiner** [comment]
We pull the exchange prices for currencies, not listed on Coinbase, from Cryptocompare: https://www.cryptocompare.com/coins/kreds/overview
0.0000012 BTC/KREDS x 157.75 KREDS = 0.0001893 BTC
At least the internal calculation is correct :) So the price reported by Cryptocompare must be off:
it seems, that Cryptocompare polls Graviex as only exchange for KREDS. Looking at the reported price at Crypto-Bridge: 0.00000009 BTC/KREDS it differs by factor 13.
This problem arises always, in the case we have to monitor a very low volume coin.
What could be done: 
- just ignore, because we know it might be off due to low volume
- add the Crypto-Bridge API to our internal calculations

**Comment by hernandn01** [comment]
perhaps this will help, I use Crex24 for Sono and they list correctly Kreds, still they do not have Traid
https://api.crex24.com/CryptoExchangeService/BotPublic/ReturnTicker

 "PairId": 489,
      "PairName": "BTC_SONO",
      "Last": 0.000018910000000,

 "PairId": 294,
      "PairName": "BTC_KREDS",
      "Last": 0.000000070000000,
