### ISSUE TITLE
Zergpool Ethash not appearing

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2057]
I have 4 instances of rainbow miner in 4 different pc's with 1 rx550 each. None of them is "reading" that zergpool have ethash algo as well. I tried both zergpool and zergpoolcoins as options, but the result was the same. Any ideas?

**Comment by CadenceMTk** [comment]
Hi 

what memory size is that 550? 4gb wont mine very well if at all. better to mine etc or other coin.

**Comment by papadrams** [comment]
I am talking about the other ethash algos zergpool has. Not ETH... TSF,AKA,Nilu, etc..

**Comment by RainbowMiner** [comment]
> I am talking about the other ethash algos zergpool has. Not ETH... TSF,AKA,Nilu, etc..

Am I right, that you are currently using module "ZergPool" ? If that's the case, the minimum req. for GPUs to mine with Ethash algorithm will be that of Ethereum. It uses the maximum of all the Ethash coins since you cannot know which coin is currently be mined at ZergPool. If you want to get Ethash working, use "ZergPoolCoins" (you can use ZergPool and ZergPoolCoins side by side, but then better specify the coins to mine with parameter CoinSymbol in pools.config.txt, section ZergPoolCoins).

The difference between the modules ZergPool and ZergPoolCoins is simple: ZergPool module let's ZergPool decide which coin to mine with the algorithms, ZergPoolCoins let's RainbowMiner decide which coin to mine. Personally, I prefer the ZergPoolCoins module on my rigs.
