### ISSUE TITLE
Linux Rig Won't Recognise Server

### ISSUE THREAD

**Issue by acos0874** [RainbowMiner/RainbowMiner#2061]
All other rigs are fine. I've tried by IP address and using a different rig as a server. Any suggestions please?
[debug_2022-05-06.zip](https://github.com/RainbowMiner/RainbowMiner/files/8642309/debug_2022-05-06.zip)

**Comment by RainbowMiner** [comment]
I will browse your Debug file tomorrow.

**Comment by RainbowMiner** [comment]
It seems like the Linux doesn't know how to resolve the server name or the call to the server is blocked on it's way from client to server: the network reply is "Resource temporarily unavailable" while contacting the server.
Two things you can try out:
- add an outbound rule to the firewall on the client machine
- use the IP address of the server instead of the server's name in config.txt
- check, if the call is being blocked by the server's firewall (look into the firewall's logs).

**Comment by acos0874** [comment]
Ok I'll try using a fixed IP. Thanks.
