### ISSUE TITLE
Unclean Shutdown Alerts

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#2066]
I get these warnings on Pushover when I start up RainbowMiner.  What do they mean?  Everything seems to be working properly.  Is RainbowMiner pushing the warning out from a previous shutdown?

**Comment by RainbowMiner** [comment]
Yes - if the last shutdown wasn't by pressing "X", "R" or "U" it is considered as unclean. E.g. if the rig has been rebooted without shutting down Rainbowminer.

**Comment by jch9678** [comment]
By the way, along the same lines, I get a lot of Pushover Notifications that say ComputerX has gone offline.  I log in right away and everything seems fine.
[debug_2022-05-11.zip](https://github.com/RainbowMiner/RainbowMiner/files/8672813/debug_2022-05-11.zip)
Here's a debug file of one that just happened.  I've noticed it seems to happen with Take2 more often than others but maybe that's because it's the most profitable one now.  Task Manager reports that all cores are 100% utilized even though I have CPU Affinity set.  Maybe Take2 is ignoring the affinity.

**Comment by RainbowMiner** [comment]
> Maybe Take2 is ignoring the affinity.

That's the thing - Xmrig in particular has a special way to handle Take2/Ghostrider. Since Take2 is a randomly switching concatenation of subalgorithms, Xmrig ignores the affinity setting for the benefit of automatic individual (sub-)algorithm trimming. That can lead to 100% CPU for some algorithms. Personally, I am not a big fan of that strategy. Luckily the Xmrig developers give us one setting to influence the maximum affinity a bit. It's `    "max-threads-hint": 50,` in `.\Bin\ANY-Xmrig\config_Take2_1xYourCPUsName_0x5555_8.json`. The parameter is in percent, e.g. 50% tells Xmrig to "try to not put more load than 50% on the CPU". But it's a hint, only.

You can change the parameter in the specific config file, the setting will persist. Actually, RainbowMiner already tries to preset that value according to your "CPUMiningThreads" setting. It's set to CPUMiningThreads / CPUMaxThreads x 100 at the first start of Xmrig with a specific affinity/threads number. Have a look at the config's filename - it contains the affinity and threads: `config_Take2_1x<YourCPUsName>_<CPUMiningAffinity>_<CPUMiningThreads>.json`

**Comment by jch9678** [comment]
This is what I've been using per your suggestion here: https://github.com/RainbowMiner/RainbowMiner/issues/1109#issuecomment-664328968

"CPUMiningThreads": 22,
"CPUMiningAffinity": "0xFFFFF5",
"EnableAutoAdjustAffinity": "0",

EnableAutoAdjustAffinity doesn't have to be set to 1 in order for RainbowMiner to work with XMRig correctly does it?

**Comment by RainbowMiner** [comment]
Yes, this setting is perfect for all CPU miners - except for Xmrig mining Take2. Just manually edit the take2 json config file `.\Bin\ANY-Xmrig\config_Take2_1x<YourCPUsName>_0xFFFFF5_22.json` and set the `"max-threads-hint": 50,` for a start. If all runs smoothly, you can gradually increase the value in steps of 5 (for example).

**Comment by jch9678** [comment]
ok, thanks, will do.
