### ISSUE TITLE
Stuck on reading config

### ISSUE THREAD

**Issue by rizkyaulya** [RainbowMiner/RainbowMiner#2075]
![image](https://user-images.githubusercontent.com/44210627/169750349-343e8903-6333-4cab-9b7d-70753dddc358.png)

On of My RIG suddenly stucking on that status.
I tried to use backup config but it didn't help

**Comment by rizkyaulya** [comment]
Well, it working again after stuck for hours. Right after I posted this issue 😂

**Comment by rizkyaulya** [comment]
Hi, there was a power outage at my place. This RIG seems to be stuck again for 3 hours liek this:

![image](https://user-images.githubusercontent.com/44210627/170659255-7fbda512-849f-4502-a1c2-6d46c7931216.png)

I closed the window and start the RBminer again. now it seems works.
is there anything I can do to prevent this issue in the future?

**Comment by RainbowMiner** [comment]
It would be very interesting to see, at which point it has stopped, during the configuration read process. Could you please create and upload a Debug file?

**Comment by bwstandard** [comment]
If you push buttons does it go? I'm assuming not. 

I do have times where it just freezes out of the blue. 

Superstitiuosly I leave task manager open. Seems to work.

**Comment by rizkyaulya** [comment]
@RainbowMiner 
it stuck here:
![image](https://user-images.githubusercontent.com/44210627/171450114-afd419e0-bad9-4f9a-9d6d-90f657104487.png)

I restarted it after 3- minutes and now still in the same condition

**Comment by rizkyaulya** [comment]
> @rizkyaulya just restart RainbowMiner, then create that debug file. It will contain the last hang. I suspect, this has something to do with internet connectivity. We will get to the bottom of this.

![image](https://user-images.githubusercontent.com/44210627/171450355-19640a4d-049c-4a55-b6c6-9bc0af9b805d.png)

@RainbowMiner it stucking on that. I restarted 4 times. now it's been 30 minutes

**Comment by RainbowMiner** [comment]
Thank you! I will check this debug file asap

**Comment by RainbowMiner** [comment]
Ok, I have found the following four warnings in the log files. Especially the first is one of major concern.

> Get-NetFirewallApplicationFilter: Not enough memory resources are available to complete this operation.

Please check the Windows10 resources on that machine. Try to furthermore increase the swap file size. 
It also may be the case, that there is a hardware failure. Have a look for yellow exclamation marks inside the device manager.

> The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find a process with the process identifier nnn.

This is caused by the OverdriveNTool.exe call, that you have put into the autoexec.txt. It seems, that this tool tends to crash too, if the memory resources are a problem (see warning number one).

> WARNING: Failed to communicate with MSI Afterburner

Is the Afterburner installed and running? If yes, check, if it can access the GPUs correctly or if it is stuck as well, when the problem occurs.

> WARNING: This rig's system time is off by -80 seconds. Please adjust and restart RainbowMiner!

This is minor, but can cause trouble. Please adjust the system clock.

Hope these hints help a bit. My gut feeling points to a GPU hardware issue.

**Comment by rizkyaulya** [comment]
Thank you, There is some issue with the network and firewall. 
I found some solustion by disableing some windows services.

ON those RIG I also using storj, so it make some network conflict
