### ISSUE TITLE
autoupdate functionality?

### ISSUE THREAD

**Issue by ebojali** [RainbowMiner/RainbowMiner#21]
Is there any plan to have a autoupdate functionality for your SW? I think it would be much appreciated so that you don't need to copy stats, configs etc to the newly downloaded SW.

**Comment by RainbowMiner** [comment]
Yes, I currently design an autoupdate functionality.

RBM

**Comment by ebojali** [comment]
Alright, thanks alot for that!

**Comment by ebojali** [comment]
Thanks I Will try it out.  Do you have a lazy on how to make localhost:4000 accesable outside the mining computer? I like the web part very much!

//Bojan

**Comment by RainbowMiner** [comment]
I am already working on a remote API. It is not that easy :)

**Comment by ebojali** [comment]
I couldn't just download the patch and replace the files, it did not work for me so I had to download the new release.

**Comment by RainbowMiner** [comment]
Yes, this happens when RainbowMiner had to re-download all the miners. It keeps track of when it downloaded a miner and compares this date against the statistics. If the download-date is newer than the last run of a miner, it get's the "Needs Benchmark".

In the future, with the automatic update function, this problem should never happen again.
For your current setup, I created a little batch file [TouchBenchmark.bat](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/TouchBenchmark.bat) (use right-click "Save file as.." and save it into your RainbowMiner directory)

The doubleclick on the TouchBenchmark.bat and the "Need Benchmark" should be gone.

RBM

**Comment by ebojali** [comment]
Great, It worked fine.. 
![image](https://user-images.githubusercontent.com/35561346/44263404-1b451c00-a21f-11e8-8416-39858f0cdacd.png)

**Comment by RainbowMiner** [comment]
Very good :) I will close this issue now.
