### ISSUE TITLE
New amd fail to be recognized regularly. 

### ISSUE THREAD

**Issue by Nickfost** [RainbowMiner/RainbowMiner#2118]
I just set up a brand new 8 card x080 rig not only does it incorrectly name the card but often has the wrong quantity of cards after a restart. Sometimes it shows zero cards and I have to force restart it

**Comment by RainbowMiner** [comment]
Could you please upload a debug file? Then I can check what's going on with the naming of the GPUs. 
Missing cards are normally a sign, that there is something wrong with the hardware setup. In many cases it's a timing problem during reset caused by very high currents, that will force the PSU to ramp up slowly or erratic. What helps would be to use a PSU with very good response times.

**Comment by Nickfost** [comment]
@RainbowMiner anything?

**Comment by Nickfost** [comment]
some logs show 8. some show 2, some show 1.


hive always shows 8

@RainbowMiner

**Comment by Nickfost** [comment]
Doing some tests, im trying to make sure we are using all known good hardware. 

Is anyone else using X080 cards successfully?

**Comment by Nickfost** [comment]
Can confirm if 2, 4, or 8 cards are in either of two rigs running hiveos correctly identifying 2 ,4, or 8 cards rainbow miner incorrectly shows 0,1, or at most 2 cards. 

On a windows test rig, 4 cards show up perfectly fine in both windows and rainbowminer (as 6700 cards)

I've tested 3 psus, 3 motherboards, two operating systems, 4 installs (3 hiveos, 1 windows) out of paranoia as you suggested i may have faulty hardware. 

I've concluded i DO NOT HAVE ANY FUALTY HARDWARE as i have tested each part in 2 or more than 2 configuration scenarios

**Comment by Nickfost** [comment]
pls sir, halp @RainbowMiner
