### ISSUE TITLE
SkipEditionCheck Error

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#217]
I get this error upon restart after updating to 3.8.8.8, I think it was

Import-Module : A parameter cannot be found that matches parameter name 'SkipEditionCheck'.
At C:\Users\Turbo\Desktop\RainbowMiner\RainbowMiner.ps1:173 char:118
+ ... s\NetSecurity\NetSecurity.psd1" -ErrorAction Ignore -SkipEditionCheck
+                                                         ~~~~~~~~~~~~~~~~~

**Comment by RainbowMiner** [comment]
Which powershell version are you using? The SkipEditionCheck flag has been added with Powershell 6.1. I will include a fallback to older versions.

**Comment by jch9678** [comment]
yuk,  it looks like v1, it's in the v1.0 directory.  Is that possible.  I can update.

**Comment by RainbowMiner** [comment]
Would be very good, yes. PowerShell Core 6.1 is very much better.

Install PowerShell 6: [Download Installer for version 6.1.0](https://github.com/PowerShell/PowerShell/releases/download/v6.1.0/PowerShell-6.1.0-win-x64.msi)

Finally: check, if Powershell 6 is in your PATH, because RainbowMiner will not run correctly, if the path to powershell is missing. Sometimes "C:\Program Files\PowerShell\6" has to be added manually to the PATH environement variable after installing Powershell 6.1.0. Here is a nice tutorial, how to add to PATH environment variable https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/amp/

**Comment by RainbowMiner** [comment]
Ok, I added a version check before using -SkipEditionCheck flag
