### ISSUE TITLE
what is this btc wallet address ?

### ISSUE THREAD

**Issue by astitsa** [RainbowMiner/RainbowMiner#2170]
![image](https://user-images.githubusercontent.com/97480060/192128969-b0133e81-a067-44a3-9ae6-1fa68543c70f.png)

one of my rig is mining ccallium via mrr pool without a rent and not in benchmark

plus it happened multiple time for long period

**Comment by RainbowMiner** [comment]
Could you please upload a Debug file?

**Comment by astitsa** [comment]
[debug_2022-09-25.zip](https://github.com/RainbowMiner/RainbowMiner/files/9640178/debug_2022-09-25.zip)

**Comment by RainbowMiner** [comment]
Ok, I have an idea what could have happened, so please try out that changed `Core.psm1` file on your rig: https://github.com/RainbowMiner/RainbowMiner/raw/master/Modules/Core.psm1
Download it into the RainbowMiner's `.\Modules` folder (right-click -> save as), then restart RainbowMiner.

**Comment by RainbowMiner** [comment]
Wait a second, please. That module needs another change.

**Comment by RainbowMiner** [comment]
Ok, now you could give it a try:
https://github.com/RainbowMiner/RainbowMiner/raw/master/Modules/Core.psm1
Download it into the RainbowMiner's `.\Modules` folder (right-click -> save link as ...), then restart RainbowMiner.

**Comment by astitsa** [comment]
Ok thanks i will try this

**Comment by astitsa** [comment]
by the way do you know what is this wallet address for ?

**Comment by RainbowMiner** [comment]
> by the way do you know what is this wallet address for ?

Sure, that's my wallet - it is used to benchmark MRR algorithms, for which there is no pool setup on that rig. That makes sure, that there will be a MRR rig created for all possible algorithms, so that there is no need for the user to configure loads of pools/wallets. In your case, the watchdog had disabled all other Allium pools, because of the benchmark-bug (which is now solved).
