### ISSUE TITLE
KawPow algorithm missing

### ISSUE THREAD

**Issue by sfalas01** [RainbowMiner/RainbowMiner#2179]
**Hardware:**
Sapphire Radeon RX580 4GB Nitro+
**OS:**
Windows 11 Pro
**Drivers:**
[AMD Adrenalin 2022 Edition 22.3.2](https://drivers.amd.com/drivers/amd-software-adrenalin-edition-22.3.2-win10-win11-march24.exe)
**Version:**
[RainbowMiner v4.8.6.5](https://github.com/RainbowMiner/RainbowMiner/releases/tag/v4.8.6.5)

**Description:**
For some reason, RBM does not show KawPow as an eligible algorithm on any miner (except SRBMiner for some reason) even though a lot more miners support this algorithm.
Edit: The SRBMiner indication is only there sometimes. It appears and disappears with no apparent pattern. Every other miner has KawPow always unavailable.

**Comment by sfalas01** [comment]
Attaching, associated debug files
[debug_2022-09-30.zip](https://github.com/RainbowMiner/RainbowMiner/files/9684194/debug_2022-09-30.zip)

**Comment by RainbowMiner** [comment]
This is most probably a DAG size issue. The RVN DAG has already 3.57GB - all miner modules check the GPU VRAM size against this value. Since Windows blocks aprox. 12.5% of the VRAM for it's use, there is just 3.5GB left over. For SrbminerMulti I have an outdated memory check in place (just substracting 0.25GB from the total of 4GB), so that's the reason that miner still shows up.
My question: does SrbminerMulti still mine KawPow on RVN correctly, or does it crash?

**Comment by sfalas01** [comment]
> 

It does work correctly and everything else does, when miners are used independently.

Frankly, I am not sure why everyone assumes that Windows blocks the VRAM when it doesn't. It's just like an Internet myth that someone started and everyone accepted without question. Windows only blocks a small amount of VRAM on the GPU that is used as a primary display GPU (which in my case, it's the iGPU from the CPU). So I can take full advantage of the 4GB available. on all those GPUs

**Comment by RainbowMiner** [comment]
Ok, that last commit should do the job.
