### ISSUE TITLE
Feature Request - Negative Profit level

### ISSUE THREAD

**Issue by jeromemorignot** [RainbowMiner/RainbowMiner#2254]
Profitability is really low these days if any :(

I was wondering if a parameter could be set to allow a small loss in profit...like -$0.10 for example. Right now, if I select "check profitability" it has to be >0 to mine, I would be ok with a small loss especially to heat my garage...if that makes sense?

Thank you !!!

**Comment by smyers63** [comment]
I'd like to see that feature, too.  Right now, I'm setting my electricity cost low so that I get mining and the heat that comes with it.

**Comment by jeromemorignot** [comment]
> I'd like to see that feature, too. Right now, I'm setting my electricity cost low so that I get mining and the heat that comes with it.

That's what I do too - but I can't really control how much it really costs me and I can't really control the acceptable loss...thus my request.

**Comment by smyers63** [comment]
Understood.  That's why I'd also like that feature.

**Comment by jeromemorignot** [comment]
Woooow man---you are fast! Thank you!

**Comment by jeromemorignot** [comment]
@RainbowMiner I have been testing the new feature - I don't think it's working: 
Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (CPU#00)
=================================================

Miner              Fee Algorithm       Speed   Diff Power     BTC/Day USD/Day   TTF Accuracy Pool                  PoolFee Wallet
-----              --- ---------       -----   ---- -----     ------- -------   --- -------- ----                  ------- ------
Xlarig               - Panthera    2.26 kH/s 79.64k   53W -0.00000450  -0.081   4 m      95% MoneroOcean-XLA         0.68% 84Y..3LY
CpuminerArctichash   - ArcticHash 56.34 kH/s      -   62W -0.00000653  -0.118 1.2 h      23% ZpoolCoins-GLT-arctic   1.00% RVk..KSt
CpuminerJayddee      - MinotaurX   2.58 kH/s      -   54W -0.00000543  -0.098 6.7 m      93% ZpoolCoins-MAZA         1.00% RVk..KSt

Status:
WAITING FOR PROFITABILITY
 (be patient or set CheckProfitability to 0 to resume)

My parameter in the config file is:
"ProfitabilityLevel": "-0.00002"

Thanks!

**Comment by RainbowMiner** [comment]
@jeromemorignot since you have closed that issue, let me ask, did it work or not?

**Comment by jeromemorignot** [comment]
No, it didn't. But I opened a new issue for it. This thread was forvthe feature itself so I thought I should open a separate issue just for the not functioning aspect.

**Comment by smyers63** [comment]
I had a chance to try it today.  First, I set the ProfitabilityLevel in config.txt to -0.0001 and increased the electricity cost.  RBM wouldn't mine because of 0 profitability, so I decreased the electricity cost and waited for the next run with the new cost.  I had to do that several times until the cost was barely over what it was before this test.  There was still no mining with negative profit.

At that point, I decided to check the Setup page in the localhost.  There's a ProfitabilityLevel there, too (in Electricity Cost and Handling), and it was still set at 0.  I changed it to -0.0001.  Then, I got mining and started increasing the electricity cost again to watch for a negative profit.  I only ever got positive profit or nothing.  The last conditions I saw were the following:

GeForce RTX 3080 (GPU#01), GeForce RTX 3090 (GPU#00,GPU#02)
===========================================================

Miner             Fee Algorithm                                   Speed  Diff Power     BTC/Day USD/Day    TTF   Accuracy Pool                               PoolFee Wallet
-----             --- ---------                                   -----  ---- -----     ------- -------    ---   -------- ----                               ------- ------
SrbMinerMulti   0.85% HeavyHash                               2.63 GH/s 16.96  827W -0.00000504  -0.100 17.5 m        67% RPlant-OBTC                          1.00% bc1..5n6
Gminer        2.00%,- {Autolykos2, kHeavyHash} {734.65 MH/s, 1.69 GH/s}   -,-  847W -0.00005269  -1.043 {-, -} {88%, 93%} {unMineable-ETHW, NiceHash} {0.75%, 2.00%} {ETH..9z9, 3C1..6cq}
Gminer          5.00% Cuckaroo30                             16.79  H/s     -  830W -0.00006118  -1.211 17.3 s        92% 2Miners-CTXC                         1.00% 0xe..0f2

GeForce RTX 3090 (GPU#00,GPU#02)
================================

Miner             Fee Algorithm                                   Speed  Diff Power     BTC/Day USD/Day    TTF   Accuracy Pool                               PoolFee Wallet
-----             --- ---------                                   -----  ---- -----     ------- -------    ---   -------- ----                               ------- ------
SrbMinerMulti   0.85% HeavyHash                               1.83 GH/s 14.54  544W  0.00000219   0.043 17.5 m        67% RPlant-OBTC                          1.00% bc1..5n6
Gminer        2.00%,- {Autolykos2, kHeavyHash} {517.69 MH/s, 1.04 GH/s}   -,-  575W -0.00003602  -0.713 {-, -} {88%, 93%} {unMineable-ETHW, NiceHash} {0.75%, 2.00%} {ETH..9z9, 3C1..6cq}
Gminer          5.00% Cuckaroo30                             11.35  H/s     -  561W -0.00004134  -0.819 17.3 s        92% 2Miners-CTXC                         1.00% 0xe..0f2

Status:
WAITING FOR PROFITABILITY
 (be patient or set CheckProfitability to 0 to resume)

From that, it looked like RBM should have been mining, either positive or negative (up to -0.0001/-$1.90).
