### ISSUE TITLE
(ErrorActionPreference) Error causing restart of pc

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2284]
Hallo,
I am getting this error on one of my rigs: 
PS>TerminatingError(ConvertFrom-Json): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot bind argument to parameter 'InputObject' because it is null."

This is causing my gpus to stop mining and after a while it restarts the pc.
Any idea whats causing it? 
[debug_2023-01-28.zip](https://github.com/RainbowMiner/RainbowMiner/files/10526621/debug_2023-01-28.zip)

**Comment by RainbowMiner** [comment]
It looks like, it's the other way round: the GPUs (or one of it) seem to crash. This causes the miner to hang and RainbowMiner cannot read the miner's API any longer. Since it is the miniZ miner: this one has an auto-reboot build in, in case a GPU is falling of the bus. So maybe check your GPUs, check if they are still seated correctly, if the cooling is running and if they are clean and not covered under a blanket of dust.

**Comment by papadrams** [comment]
I suspected something like that. Thats why for the last 3 days i have handpicked 7 most profitable algos and entered them in allowed algos. All good so far. How can i see what miner and algo was running when it kept failing?
