### ISSUE TITLE
Prohashing PPS adjustment

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2330]
Hallo again!
I have 2 issues with Prohashing.
I have chosen prohashing as pool and input the necessary info.
In a rig with 8 gb cards it detected some algos but not all.
In a rig with (3) 4gb cards it detected even fewer. I guess its because of the dag file in Kawpow(RVN) and Ethash(ETHW). So i tried Prohashingcoins there. Unfortunately no algos (coins)  were avaliable to mine.

Also, this pools works with either pps or pplns. 
Shouldnt we be able to choose what payment scheme we want?
Also when pps is selected, TTF, maxtimesincelastblock and maxalloweluck should not be applicable. You are getting payed whether the pool has found a block or not. Thats propably a reason why some algos never appear.

**Comment by papadrams** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/36564393/227363507-f0b9451c-8846-4481-bfbe-138d3a594020.png)
On this gpu, Etchash and Autolykos2 is missing. Also check the pool fee. In theory it should be 3.99 in every algo. Same issue with pool fee on cpu algos as well

**Comment by RainbowMiner** [comment]
Regarding the payment scheme: we can select the scheme for ProHashingCoins only. By adding "@pps" or "@pplns" to the username in "User" inside pools.config.txt (e.g. `"User": "rbm@pplns",` will mine for username rbm with pplns scheme). ProHashing doesn't allow PPLNS for their default algorithm select mining. So it's really only there for ProHashingCoins.

The pool's fee is being delivered via the pool's API, so either their API gives us the wrong data or the fee is in fact lower for the specific algo/coin.

Looking closer into the ProHashingCoins pool module - you currently need to specify the coins to mine in "CoinSymbol" in pools.config.txt. If that field is empty, no coins will be selected. I think this is the wrong approach, so let me change the module accordingly (in the meantime put many coins in there)

Regarding TTF and timesincelast - you are right. For PPS it's not important since it simply shifts rewards into the future, but you will get paid for each submitted share, no matter what. Just set "MaxTimeSinceLastBlock" and "MaxTimeToFind" to something high enough. Maybe "48h" - that's two days. You do not want to mine an algo that hasn't delivered one block within the past 48h.
