### ISSUE TITLE
reading and understanding the logs

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2354]
im not sure if other have this same issue but one of the miners will hold on to my card for too long and lock it up....so when it switches to the next miner it is missing a card... sometimes 2... it has to do with msi and overclocking i think.... i just dont know where in the log to see what the culprit app is... in the past i watched bzminer do it so i disabled it and the problem went away... its back and i dont know where to look in the logs to find the culprit mining app

**Comment by RainbowMiner** [comment]
Could you please create and upload a Debug file?

**Comment by whitindllc** [comment]
here are some more logs after it shutdown a card
[debug_2023-04-25.zip](https://github.com/RainbowMiner/RainbowMiner/files/11319645/debug_2023-04-25.zip)
[debug_2023-04-24(2).zip](https://github.com/RainbowMiner/RainbowMiner/files/11319646/debug_2023-04-24.2.zip)

**Comment by RainbowMiner** [comment]
If a Nvidia GPU drops out, it's most probably due to an (GPU memory) overclocking issue, since some algorithms run pretty hot on the memory. In the case, that the GPU drops off the grid, only a reset of the drivers (or reboot) helps. I would either reduce the overall memory overclock or start using the RainbowMiner OCProfiles. For the most critical algorithms/miners, RainbowMiner will already use reduced memory OC.

- First of all, make sure, that "Force P2 State" is set to Off: https://github.com/RainbowMiner/RainbowMiner/issues/36
- Then enable OCProfiles (set `"EnableOCProfiles": "1",` in config.txt), then check and adjust the OC values in ocprofiles.config.txt:
  - https://github.com/RainbowMiner/RainbowMiner#overclocking-overview
  - https://github.com/RainbowMiner/RainbowMiner#oc-option2-custom-overclocking-profiles

**Comment by whitindllc** [comment]
the overclock is set the same all on all of the cards.... i would take tbe time to create OC profiles and such for sold and hot algos but there is no fan congtrol option... the a4000s need to run at 100 percent fan which so far i found i can only control from MSI.... even with a 0/0 overclock profile in MSI this still happens

**Comment by RainbowMiner** [comment]
I have MSI Afterburner handling the fan control - it's running alongside RainbowMiner for that one task only. All other OC will be set by OCProfiles. There are already some defaults in the database, though I am not sure if there are any for the A4000. 

> even with a 0/0 overclock profile in MSI this still happens

For some cards/algorithm even that might be too much to handle.
Have you already set "Force P2 State" to "Off"? If no, 0/0 refers to P2 state and in case a miner starts or stops, the GPU might shortly bump into P0, which boosts the oc for a very short period. That boost off-on-off can easily push a GPU over the cliff.

In the logs you search for keyword "crashed". Most of the time, as soon as a GPU falls off the grid, the miners start to crash at startup. If there are crashes in every round after that, you will know which algorithm killed the GPU.

**Comment by whitindllc** [comment]
which log?? there are quite a few in this zip file

Also the word crashed is on every line in the activity log.... should i be looking for crashed :0 or crashed :1? 

the miners continue to work just fine... i just lose 1 or 2 of the a4000's....

**Comment by whitindllc** [comment]
I think i figured out what actually happens... i tried all of the stuff above and the results the same..... using your oc or msi....

i did nothing that while switch between miners that it over rode my setting of 100 fan on one the cards that always fails... i think that card must overheat and then gets shut off.... i may need to try the fans individual under profile 1 instead of all 1 group....

**Comment by RainbowMiner** [comment]
Oh! So there is a miner, that resets the fan oc on exit. Can you tell, which of the miners did this?

**Comment by whitindllc** [comment]
i think its miniz

**Comment by RainbowMiner** [comment]
That's unwanted behavior. I will contact the developers, because that needs a fix.

**Comment by whitindllc** [comment]
im trying to turn off the sync settings for similar GPU's to see what i will do next.... its very odd that it only does it to 1 card.. not all 3....

**Comment by RainbowMiner** [comment]
True - maybe it's the MSI Afterburner after all.

**Comment by whitindllc** [comment]
soooo with different kinds of cards how are you controlling the fans...  with all 1 msi profile or different ones?

also in the oc profiles when you change the mem and core clock you dont really specify how to do it... do you put 1150 or +1150

**Comment by whitindllc** [comment]
maybe its a device vs combo thing?

**Comment by whitindllc** [comment]
> I have MSI Afterburner handling the fan control - it's running alongside RainbowMiner for that one task only. All other OC will be set by OCProfiles. There are already some defaults in the database, though I am not sure if there are any for the A4000.
> 
> > even with a 0/0 overclock profile in MSI this still happens
> 
> For some cards/algorithm even that might be too much to handle. Have you already set "Force P2 State" to "Off"? If no, 0/0 refers to P2 state and in case a miner starts or stops, the GPU might shortly bump into P0, which boosts the oc for a very short period. That boost off-on-off can easily push a GPU over the cliff.
> 
> In the logs you search for keyword "crashed". Most of the time, as soon as a GPU falls off the grid, the miners start to crash at startup. If there are crashes in every round after that, you will know which algorithm killed the GPU.
> 
> The usual suspects are KawPow, Neoscrypt and all the dual mining combinations.

So i tried that p2 state thing and every single mining program crashed... i turned it back off but and they started working again... the issue is when using OC's and switching between miners.... 1 of the a4000 cards just stops working... and in the process drops another one off...
right now its 
0 = a4000
1 = 3060ti
2 = a4000
3 = a4000

so the mining apps all call for 0 2 3.... when card 0 crashes it seems like all the cards move up... 
0 = 3060ti
1 = a4000 
2 =a4000 
so only 0 and 2 work... and if zero is mining something solo on its own it causes everything to crash

I did notice something interesting in MSI

when card 0 crashs i cant control the fans or the power... the OC's for the core and mem go back to 0
the core clock sits at nothing but the memory clock is pegged at 8200

**Comment by RainbowMiner** [comment]
All of your description indicate, that it's 100% an overclocking problem.

When switching "Force P2-State" to "Off", have you followed through with my advice to set the overclocking values to 0/0? You will need to use lower overclocking offsets, or your GPU will be driven over the edge, since it's then always switching to P-State 0.

Let me explain:
the Nvidia GPUs have 3 to 4 different powerstates with different preset mem/cpu frequencies. 0 is the powerstate with the highest freq, the P-State 2 or 3 have the lowest freq. presets. The Nvidia drivers try to keep the GPUs at P-State 2 (that's what "Force P2-State" means). Your overclocking offsets are being added to the presets, so if you adjust your GPU overclocking to the edge in P-State 2, then (even a short) switch to P-State 0 will be drive the GPU over the edge (because the overclocking offsets will then be added to the higher presets). This short switch happens, if you suddenly stop/start the load on the GPU (like switching miners).

My advice:
- set overclocking offsets to 0/0
- set "Force P2-State" to "Off"
- use MSI Afterburner to find the new overclocking maxima and minima

After that, the GPUs will never accidently be driven over the edge, since P-State 0 is the absolute limit.

**Comment by whitindllc** [comment]
i will set the overclocks to 0/0 and turn on all of the cards.... its an issue with the a4000's and not the 3060ti or a combo of trying to use both

right now there is no overclock... lets see how long before it loses 1 of the cards

**Comment by whitindllc** [comment]
this was an overclock issue with 1 card
