### ISSUE TITLE
zergpool ethash

### ISSUE THREAD

**Issue by whitindllc** [RainbowMiner/RainbowMiner#2356]
it seems like every benchmark trying to connect to ethash.mine.zergpool.com fails... multiple miners...

did they make a change on their end?

**Comment by sfalas01** [comment]
Can confirm. There was a previous confusion with different stratum modes (stratum, ethstratum, etc) that were changed by Zergpool because of a problem with their pools. Maybe the miner strings need to be updated.
I can confirm that this is happening when using ETH-variants as well (ethash2g,3g,4g, etc). Miners currently confirmed: BzMiner, Gminer, lolminer, Rigel

**Comment by RainbowMiner** [comment]
Ok, I will double-check what's going on.

**Comment by UselessGuru** [comment]
Zergpool has a confirmed issue with all DAG based alfgosrithms caused by the pools load balancer

> ! pinpin [zergpool.com] — Yesterday at 9:09 AM
> yes, I found out issue is with our routing on eu, na and asia endpoints
> actually anycasts works from my tests yesteardday

> ! pinpin [zergpool.com] — Yesterday at 5:34 PM
> it is not resolved yet for eu and na
> only anycast works
> I will have to restart servers first, which is TODO

I will update this post as soon as I know more.

**Comment by UselessGuru** [comment]
Zergpool has still not fixed its issues with the DAG based algorithms :-(

**Comment by realsetvin** [comment]
Is this issue still occuring?

**Comment by UselessGuru** [comment]
See https://github.com/RainbowMiner/RainbowMiner/issues/2400

**Comment by whitindllc** [comment]
i pretty much excluded the ethash algos on zergpool... they are virtually useless and not profitable
