### ISSUE TITLE
Please add BLOCX to Zergpool and Zpool

### ISSUE THREAD

**Issue by IwasthefirstNerrdAlerrt** [RainbowMiner/RainbowMiner#2427]
Can you add blocx to zpool,zpoolcoins,Zergpool,Zergpoolcoins?  And maybe all the zergpool pools. Appreciate it!

**Comment by whitindllc** [comment]
are you running an asic miner?? what model?

**Comment by IwasthefirstNerrdAlerrt** [comment]
Is this asic only?  Thought it was gpu. My bad if it’s asic only.

**Comment by whitindllc** [comment]
you can mine x11 with gpu's but its probably going to make a less than a penny a day
check out whattomine.com on the top there are two tabs... asic and gpu..... each one will show you the most profitable coins to mine with each
try this..... go mine x11 on zerg or zpool manually with ccminer 2.31 ccminer alexis or ccminer klausT figure out what your best performance is.... 
then go into whattomine go into asic and click on each one of the algos under they turn grey... leave x11 blue... input your MH and it will tell you what to expect you might have to use a mh to gh calculator to figure it out because whattomine is expecting x11 to be mined in GH and not MH

**Comment by IwasthefirstNerrdAlerrt** [comment]
Appreciate the help!  I was just trying to set my wallets to match what is profitable on my miner. Doing almost $1 a day with one gpu. This is my first endeavor in mining and I’m really enjoying it. Working on a 6 pack gpu setup now. Thanks again!
