### ISSUE TITLE
Manually delete some hashrate files, benchmarks those, and then some don't come back in main screen

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#274]
Manually delete some hashrate files, benchmarks those, and then some don't come back in main screen

![image](https://user-images.githubusercontent.com/801414/47966520-2c285100-e008-11e8-9da1-7ae4e0fbe941.png)

**Comment by RainbowMiner** [comment]
Which did disappear exactly?

**Comment by RainbowMiner** [comment]
A remark: I would recommend, you remove all CpuminerJayddeeXXX.ps1 from the Miners folder, except  the CpuminerJayddee.ps1. It selects the right cpuminer-opt executable, automatically.

**Comment by paulpoco** [comment]
@RainbowMiner still not fixed.
![image](https://user-images.githubusercontent.com/801414/48101321-63029080-e1db-11e8-88ed-801620bb75de.png)

**Comment by RainbowMiner** [comment]
Thank you for bringing this up again. Thinking about it, I just figured out, what is going on: in this list, only profitable miners are being shown.  So if profitability for a miner drops below zero, it will simply not be listed. I will change the listing, so that all active miners gonna be there, no matter what profitability. It was thought to keep the list short, initially.

**Comment by RainbowMiner** [comment]
Yea, that was it. I fixed it. In the next release, miners with profit below zero will reappear.
