### ISSUE TITLE
After Computer restart lot of benchmarks and missing gpu

### ISSUE THREAD

**Issue by r0dn0r** [RainbowMiner/RainbowMiner#298]
After I updated to NVIDIA 416.81 and AMD 18.11.1 drivers and then restarted the computer I got a lot of the AMD miners starting to benchmark again and the GTX1070Ti doesn't get detected by Rainbowminer, but shows up in the GPUtest.bat results.
[debug-2018-11-09.zip](https://github.com/RainbowMiner/RainbowMiner/files/2564661/debug-2018-11-09.zip)

**Comment by RainbowMiner** [comment]
Wow, that sounds like something got really mixed up, due to the dual driver updates. 
First of all: the starting benchmarks indicate, that the GPU detection indeed failed for the Nvidia GPU.
Would you send me the gputestresults.txt in your RainbowMiner folder, please?

**Comment by r0dn0r** [comment]
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/2566011/gputestresult.txt)

**Comment by RainbowMiner** [comment]
Ok, looking at the GPU results, it looks like your GPU have swapped their OpenCL index, due to the driver updates. If you look into http://localhost:4000 - point All Devices, is the Nvidia GPU on the list?

**Comment by RainbowMiner** [comment]
Also, please extract this new GPUtest.ps1 into your RainbowMiner folder and start GPUtest.bat again. Then drop the gputestresult.txt here. It now includes OpenCL detection.
[GPUtest.zip](https://github.com/RainbowMiner/RainbowMiner/files/2566899/GPUtest.zip)

**Comment by r0dn0r** [comment]
No, the Nvidia GPU doesn't show up.
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/2567611/gputestresult.txt)
Going to reinstall the drivers now.

**Comment by r0dn0r** [comment]
Even after driver reinstall the Nvidia GPU doesn't show up.

**Comment by RainbowMiner** [comment]
Wow, this is really weird. Looking at the end of the logfile, I can confirm, that the windows OpenCL.dll delivers the AMD platform, only. My gut feeling tells me, that your system uses the wrong OpenCL.dll - I will do a brainstorm on this problem.
For worst case, I will build fallback solution into RainbowMiner, but I fear, that many miner programs will fail, too, because most of them depend on the same OpenCL.dll
Ok, but first, let me think.

**Comment by RainbowMiner** [comment]
This is how it would go:
- download https://www.guru3d.com/files-details/display-driver-uninstaller-download.html
- remove both display drivers, using the DDU tool
- now reinstall both

**Comment by RainbowMiner** [comment]
One thing:
- be sure to disable automatic windows driver update (here you find a tutorial: https://www.laptopmag.com/articles/disable-automatic-driver-downloads-on-windows-10)
- eventually run DDU in safe mode to remove old driver

**Comment by RainbowMiner** [comment]
Also, you could try to put this OpenCL.dll directly into your RainbowMiner directory: 
[OpenCL.zip](https://github.com/RainbowMiner/RainbowMiner/files/2567926/OpenCL.zip) (download the zip and unpack the dll into the folder)
.. if it works - perfect. If not, simply delete it again.

**Comment by RainbowMiner** [comment]
- have a look into the C:\Windows\System32 folder: is there an OpenCL.DLL? Which version is it?

**Comment by RainbowMiner** [comment]
- Driver installation order matters, as does which PCIe slot the cards are in as well as which one drives the output.
- Which driver had been installed first? Nvidia or AMD?
- What does [GPU-Z](https://www.guru3d.com/files-details/gpu-z-download-techpowerup.html) say?
- What do the Nvidia controls say?

**Comment by RainbowMiner** [comment]
- one important question: do (at least) some miners work with the opencl.dll in the RainbowMiner directory?

**Comment by r0dn0r** [comment]
- I did not reseat the cards and it was working that way before. The display is connected to the AMD GPU.
- The AMD driver was installed first, then a restart and then I installed the Nvidia driver.
- GPU-Z shows the Nvidia card after I start it, but crashes when I try to switch to the AMD GPU, but seems to correctly identify the AMD GPU.
- Nvidia controls only open when you attach a display to the Nvidia card.
- Apparently the miner work  at the moment. [debug-2018-11-10.zip](https://github.com/RainbowMiner/RainbowMiner/files/2568454/debug-2018-11-10.zip)

**Comment by RainbowMiner** [comment]
Ok, this is a good sign. At least the drivers do their work. What is left over is the broken OpenCL installation on your machine. Unfortunatly, many AMD miners need a parameter for the opencl platform id. This is a value, that is only being delivered with the correct OpenCL.dll

- did you already to try to install the drivers the other way round? Nvidia first, AMD second? It could be worth a shot, e.g. deinstall all with DDU, reinstall Nvidia, then AMD.

I could imagine that the following is happening, if AMD comes first:
- it installs some AMD OpenCL.dll in System32, opencl.dll in SysWOW64
- Nvidia installer sees them, checks version numbers and skips installation of their own OpenCL.dll, due to the fact the AMD dll has higher version number. Thus braking the opencl installation.

**Comment by RainbowMiner** [comment]
If this fails, too, we have one last possibility: I could (and will, if needed) add some manual override for the OpenCL detection functions to RainbowMiner.

**Comment by r0dn0r** [comment]
Ok, will do the reinstall in the different order tomorrow morning and then write an update.
Thanks again!

**Comment by r0dn0r** [comment]
Reinstalled with Nvidia first and the AMD - still didn't work. Uninstalled everything again then tried AMD 18.10.2 and Nvidia 416.81 - still didn't work. Then tried AMD 18.11.1 and Nvidia 416.64 and now both GPU's show up in OpenCL ([gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/2569748/gputestresult.txt)) and work again with Rainbowminer. Only all Nvidia benchmarks are running again.
Thanks for the help!
