### ISSUE TITLE
add disable device at device.config.txt

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#328]
1050ti are gone now. If I disable them at device manager everything benchmarks

**Comment by hernandn01** [comment]
or is there a way to select the devices wanted only?

**Comment by RainbowMiner** [comment]
> 1050ti are gone now. If I disable them at device manager everything benchmarks

The enumeration of the GPU in your computer is a windows thing. As soon as the enumeration changes, the stat files for the miners will be invalid. This is why your benchmark starts off.

If they are still plugged into your rig: you may change the config.txt, field "DeviceName". Instead of "nvidia" put in the device models of the GPU(s) you want to use. You can look them up at http://localhost:4000 , "All Devices" or "Selected Devices" column "Model".

**Comment by hernandn01** [comment]
that worked great, thanks!

"DeviceName": "GTX10606GB,GTX10603GB,CPU",
