### ISSUE TITLE
Profit per card.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#377]
Wonder if its possible for Rainbowminer to mine only when profitable per card. For those of us that have different cards in one machine. AKA 1060 may not be profitable while a 1080 will be while in the same PC?

**Comment by RainbowMiner** [comment]
> Wonder if its possible for Rainbowminer to mine only when profitable per card

It should do the job, already and mine on profitable GPU, only. I remember having spend many thoughts on that. If it does not, it may be some problem with the setup. I will have a look.

> My rigs have the same cards but is there a way in rainbow miner, for example, to tell it to only use cards 2 and 3; but open up another instance that only uses cards 1 and 4?

No, this is currently not possible because of the build-in cleanup process. This process is intended to detect crashed miners - miners that are being started by another instance will be detected as "crashed" instances. Eventually, there might be a chance to sharpen this algorithm, so that it keeps it's fingers of other instances' miners.

**Comment by RainbowMiner** [comment]
Actually, with the comeing release v3.9.2.5 it should be possible to run multiple instances of RainbowMiner on one machine. You will just have to take care to setup different API port addresses for each of the instances.

**Comment by hernandn01** [comment]
Wonder if its possible for Rainbowminer to mine only when profitable per card

It should do the job, already and mine on profitable GPU, only. I remember having spend many thoughts on that. If it does not, it may be some problem with the setup. I will have a look.

---
I can tell that this is in fact happening. a few weeks ago, with my current electricity setup, I had all 4 cards setup to mine and at times the 1050ti were stopped altogether and sometimes only the 1060 6 was mining

**Comment by RainbowMiner** [comment]
> I can tell that this is in fact happening. a few weeks ago, with my current electricity setup, I had all 4 cards setup to mine and at times the 1050ti were stopped altogether and sometimes only the 1060 6 was mining

Thank you very much for telling!
