### ISSUE TITLE
How to add new payout currency for pool

### ISSUE THREAD

**Issue by rinkal26783** [RainbowMiner/RainbowMiner#40]
I want to add new payout currency on zergpool
I have added in in this pools.config.txt 
"XVG": "DLUr2gaJbSks5JgyZDi1psrrSzhKtyq5YA",

but its not working.

**Comment by RainbowMiner** [comment]
Yes, this is the correct behavior: at this time, I fixed the payout currencies to BTC,BCH and DASH, for this pool. My intention was to keep RainbowMiner users on the safe side.
This is, what ZergPool writes on it's website:
> BTC, LTC and DASH are guaranteed payout coins, for others please check block amount we mine in pool.

Anyway :) I will open the pool settings to all possible payout currencies, so that you will be able to choose freely. But keep ZergPool's note in mind.

RBM

**Comment by RainbowMiner** [comment]
I will push a new release, so that you can easily update.

RBM

**Comment by hernandn01** [comment]
![image](https://user-images.githubusercontent.com/41829368/44688570-e18bc680-aa11-11e8-9f89-a8be325b18ad.png)
mc=coin is not getting added to the command line

**Comment by RainbowMiner** [comment]
Ah, now I understand. You want to directly mine a coin. For that, please activate pool ZergPoolCoins. The ZergPool is for auto-exchange, only.

RBM

**Comment by Byrd1083** [comment]
Hey, since this question has come up, just looking for proper configuration to mine coin VEIL at blockmasters. Would like to be paid out in that coin as well. How do I properly setup so I do not waste time please? I checked with blockmasters and they say they pay out in that coin.

**Comment by RainbowMiner** [comment]
I just checked their API and website, as well those of other pools - currently none of the autoexchange pools support veil mining. If you want to directly mine VEIL into your own veil wallet, I recommend activation of "Bsod" pool.
1) config.txt: add "Bsod" to "PoolName"
2) config.txt: remove "Bsod" from "ExcludePoolName" (or clear this field)
3) coins.config.txt: add section "VEIL" with your wallet address (or edit one that is not in use)
```
  "VEIL": {
    "Penalty": 0,
    "MinHashrate": "0",
    "MinWorkers": "0",
    "MaxTimeToFind": "0",
    "Wallet": "yourveiladdresshere",
    "EnableAutoPool": "0"
  },
```
4) pools.config.txt: find section Bsod and activate VEIL by adding the "$VEIL" - this will be substituted automatically by the value in coins.config.txt. Of course you may also input your veil address directly. I prefer keeping my wallets in coins.config.txt to be very flexible. It's super easy and error safe to add a coin to a pool like that, because there is no need for copy and paste.
```
  "Bsod": {
    "VEIL": "$VEIL",
    "Worker": "$WorkerName",
    "Penalty": 0.0,
    "User": "$UserName",
    "API_ID": "$API_ID",
    "API_Key": "$API_Key",
    "DataWindow": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "1",
    "StatAverage": ""
  },
```

**Comment by RainbowMiner** [comment]
"I checked with blockmasters and they say they pay out in that coin."
.. if they do guarantee payout in VEIL, so you might also try activation of veil as pool payout currency. It's just that there is no direct veil mining, so it will be autoexchange to VEIL, only.

Like that:
1) coins.config.txt: add section "VEIL" with your wallet address (or edit one that is not in use)
```
  "VEIL": {
    "Penalty": 0,
    "MinHashrate": "0",
    "MinWorkers": "0",
    "MaxTimeToFind": "0",
    "Wallet": "yourveiladdresshere",
    "EnableAutoPool": "0"
  },
```
2) pools.config.txt: find section Blockmasters and activate VEIL by adding the "$VEIL" - this will be substituted automatically by the value in coins.config.txt. Make sure there is no trail to "BTC" or any other currency anymore. The easiest way is to change the "BTC" to "VEIL".
```
  "Blockmasters": {
    "VEIL": "$VEIL",
    "Worker": "$WorkerName",
    "Penalty": 0.0,
    "User": "$UserName",
    "API_ID": "$API_ID",
    "API_Key": "$API_Key",
    "DataWindow": "",
    "Algorithm": "",
    "ExcludeAlgorithm": "",
    "CoinName": "",
    "ExcludeCoin": "",
    "CoinSymbol": "",
    "ExcludeCoinSymbol": "",
    "FocusWallet": "",
    "AllowZero": "0",
    "EnableAutoCoin": "1",
    "StatAverage": ""
  },
```

**Comment by Byrd1083** [comment]
So would this be a proper guide to change to a different coin other then veil as well? In other words, I can follow these steps to get paid in coins I choose by changing accordingly.

I understand blockmasters is working out there veil issue. They say it should be stable soon. I just want to keep coins I mine instead of auto exchange to BTC from now on.

**Comment by RainbowMiner** [comment]
Exactly. That's the way it works for this and every other pool.
