### ISSUE TITLE
Use Same Algo Names

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#409]
Could you use the same algo name across the files and displays.  For example in the config file we have to use equihash144 but the console displays equihash24x5.

**Comment by RainbowMiner** [comment]
> equihash144 but the console displays equihash24x5

Thank you, I will change the defaults to the standard names.
Anyway, you are free to use any of the names in the config files, since they all get parsed. So, basicly, every equihash1445, equihash144, eqihash24x5 will be translated to Equihash24x5, internally.

**Comment by RainbowMiner** [comment]
Personally, I prefer (and propagate) the use of "Equihash<number>x<number>", since it appears more logical to me. There are some notes on that in our Readme: https://github.com/RainbowMiner/RainbowMiner#special-notes-for-equihash

But it all depends on your personal preference. You might as well use "Equihash144", "Equhash150" etc.
