### ISSUE TITLE
endless benchmark with 3.9.6.0

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#417]
Benchmarking is stuck for gtx1060 3Gb for Equihash on Gminer. I had previously disable at device level but it is not working anymore
 "GTX10603GB": {
   "Algorithm": "",
   "ExcludeAlgorithm": "Ethash,Equihash24x7,Equihash25x5,equihash24x7,equihash25x5",

the miner keeps crashing and starts to benchmark again

**Comment by hernandn01** [comment]
I upped the min memory to 4Gb in Gminer and it let me continue

**Comment by RainbowMiner** [comment]
Ooops! Thank you for bringing this up. It points directly at a tiny bug in the new benchmark core. I fixed this, so that infinite benchmark loops of crashing miners will no longer happen. After three fails the miner will be disabled.

**Comment by RainbowMiner** [comment]
> I had previously disable at device level but it is not working anymore

Was it probably another Equihash that crashed Gminer, than those, that you have deactivated in the devices.config.txt? If it has been Eq24x7 or Eq25x5: if you find the time, please send me a current "Debug file", so that I can have a look. 
By the way, Rainbowminer does not care about upper/lower case. 

It's safe to use just this:
```
"Ethash,Equihash24x7,Equihash25x5",
```

**Comment by hernandn01** [comment]
I think the problem was a missing comma couple of lines below on the device.config caught that on the next restart. Thanks for fixing the issue that kept benchmarking after miner crashed
