### ISSUE TITLE
Missing coin label in list

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#424]
Hi!

In the Status: Running and Status: Idle table some miners aren't showing the Coin mined:
![image](https://user-images.githubusercontent.com/34612740/52659113-5cbb3900-2edb-11e9-9eb9-8b3b0ba49a14.png)

![image](https://user-images.githubusercontent.com/34612740/52659042-3d241080-2edb-11e9-9e5c-2b2d0d1f18bb.png)

It would be also nice in the list of miners to also have the Coin column:
![image](https://user-images.githubusercontent.com/34612740/52659198-8f653180-2edb-11e9-96e3-27a0641d6038.png)

**Comment by RainbowMiner** [comment]
> In the Status: Running and Status: Idle table some miners aren't showing the Coin mined

This is the correct behavior: if you are mining at an automatic pool like Zpool, Zergpool, that offers multiple coins for one algorithm, it is not clear, which coin is currently being mined. It's only clear, if there is only one coin being offered. Or, otherwise, if you are mining using a coins pool like ZergPoolCoins, or solo and party mining.

> It would be also nice in the list of miners to also have the Coin column

This lists the available (fastest) miners for a specific algorithm. The coin being mined is not being known at this time, because the miners are not yet associated with a specific pool. Looking into localhost:4000, it corresponds to the "Miners" list. 

If you want to see the current miner/pool combinations including coins, just open http://localhost:4000 and open the "Active Miners" list.
