### ISSUE TITLE
Look into ZIL Mining

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#435]
I don't know much about mining ZIL but this guy says dual mining is easy and not resource intensive at all because the pow cycle is only 30 seconds for every 3 hours.  Maybe you want to look into it, I'm not sure if it's on any nicehash-type pools but it is listed on well known exchanges.

https://bitcointalk.org/index.php?topic=5110786.0

**Comment by RainbowMiner** [comment]
Thank you for this! I will have a look!

**Comment by AnthonyBe** [comment]
Came here to ask if some ZIL mining pools could be added?

There's a list of there here - https://miningpoolstats.stream/zilliqa - ezil.me, rustpool.xyz, shardpool.io, k1pool.com, comining.io

Miner instructions here - https://dev.zilliqa.com/docs/miners/mining-getting-started/

**Comment by RainbowMiner** [comment]
I have been looking into this from time to time, but must admit, that I had it put onto the waiting list - I'll give it another shot :)

**Comment by AnthonyBe** [comment]
Thank you! I tried to have a crack at adding the Ezil pool using the new userpools feature but not having much success so far.

**Comment by RainbowMiner** [comment]
Yes, I know it's tricky. I'll get it working.

**Comment by gurkburk76** [comment]
I saw this that inspired me to see if indeed a dual mining option would be sane to implement in rbm, https://www.youtube.com/watch?v=83KU1AE2kN0

I'de like to comment on this and specially dual mining since i'm sure that with the amount of possible combination of different coins and pools it can get quite complex to figure out if it's profitable or not/if it should change pool and/or algo.
Something along the lines in the setup like this:
would you like to enable dual mining?
(if yes, what pools, coins etc, remember to create a walled for whatevr coin and input it here etc etc)
Then rbm does it's magic and uses dual mining if it's actually profitable etc. I'm sure it can get quite complex but start out small :)
