### ISSUE TITLE
rainbow miner will not start

### ISSUE THREAD

**Issue by henry18341834** [RainbowMiner/RainbowMiner#436]
i have an issue with the miner not starting. i have tried to go back to other revisions but no luck. have also tried to delete the old revisions but also no luck. attached is a screenshot of what shows up before this disappears and then nothing.

![screenshot 4](https://user-images.githubusercontent.com/10469825/53058101-cf9a5600-347f-11e9-9af2-d40f5e832fc7.png)

**Comment by RainbowMiner** [comment]
This looks bad! Eventually, try to re-install the powershell 6.1

https://github.com/PowerShell/PowerShell/releases/tag/v6.1.3

**Comment by henry18341834** [comment]
ok, that did not work. anything else to try??

**Comment by RainbowMiner** [comment]
Try this: zip the Logs folder in your RainbowMiner root and drop it. If we are lucky, there is some hint buried in the logs.

**Comment by henry18341834** [comment]
since i cannot run rainbow miner i am running nemos. it uses powershell and it works.
see attached zip file for the logs. i also restored the computer to a previous date and still this did not help.
[RainbowMiner_2019-02-21_20-16-12.zip](https://github.com/RainbowMiner/RainbowMiner/files/2896192/RainbowMiner_2019-02-21_20-16-12.zip)

**Comment by RainbowMiner** [comment]
Ok, these log files helped: it tries to run PowerShell 5.1

This can be solved like this:

Check, if Powershell 6 is in your PATH, because RainbowMiner will not run correctly, if the path to powershell is missing. Sometimes "C:\Program Files\PowerShell\6" has to be added manually to the PATH environement variable after installing Powershell 6. Here is a nice tutorial, how to add to PATH environment variable https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/amp/

In parallel, I will check which part of RainbowMiner is incompatible with Powershell 5

**Comment by RainbowMiner** [comment]
Maybe it is much simpler: since you did not run RainbowMiner with admin privileges, that might have caused the trouble.
- try to right-click "Run as administrator" on the the Start.bat.

**Comment by RainbowMiner** [comment]
It would be very kind, if you could try the following:
- download [test.zip](https://github.com/RainbowMiner/RainbowMiner/files/2896701/test.zip)
- extract into the RainbowMiner folder
- start "Test.bat"
- drop "testresult.txt" here for me.

**Comment by henry18341834** [comment]
i tried to run the test program you sent me. it failed to run and make any logs. the error was that no modules were found. attached is the latest logs that i found. i have finally deleted powershell 5 from the computer, but rainbow still did not run.
[RainbowMiner_2019-02-23_06-36-45.zip](https://github.com/RainbowMiner/RainbowMiner/files/2897398/RainbowMiner_2019-02-23_06-36-45.zip)

**Comment by henry18341834** [comment]
screenshot of test fail
![screenshot 1](https://user-images.githubusercontent.com/10469825/53293119-e0a6d800-379b-11e9-9530-1ff44e887652.png)

**Comment by RainbowMiner** [comment]
Ah, the test.ps1 and Test.bat need to be located in the root of RainbowMiner ("RainbowMiner-Master"), not in a subdirectory "test". It connects with the Rbm modules to do its job.

**Comment by henry18341834** [comment]
ok here you go
[testresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/2898449/testresult.txt)

**Comment by RainbowMiner** [comment]
Super, thank you. The problem is, that the OpenCL detection fails. Did you see any error messages on screen when running the Test.bat? Most probably the Nvidia drivers are broken (I bet the Windows update has smashed them).

If you start GPUtest.bat in RainbowMiner folder, it will create a file gputestresults.txt. Would you please drop this here, too?

You could try the following:
- first start "Updater.bat" in RainbowMiner folder
- try again, if RainbowMiner starts now

If the same errors happen again:
- completely remove all current Nvidia drivers (using [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html))
- now install the newest Nvidia drivers from here: https://www.nvidia.com/Download/index.aspx
- reboot the PC
- try again, if RainbowMiner starts now.

**Comment by henry18341834** [comment]
looks like the DDU program will not let me run in normal mode. i am away from my computer until the end of march so i will not be able to see if this works since i cannot remotely get to my computer in safe mode.. i will let you know as soon as i can about this. thanks for your help.
