### ISSUE TITLE
How does PowerOffset work?

### ISSUE THREAD

**Issue by paulpoco** [RainbowMiner/RainbowMiner#457]
"Set electricity cost handling
.............
PowerOffset = power offset to allow consideration for overhead power [default=0]"

Is this in Watts?

And does this affect mining?

Is there a way to set profitability so that say CPU mining idles if below a certain $x.xx amount?

**Comment by RainbowMiner** [comment]
It is kind of straight forward approach:
- PowerOffset is in Watts
- this value should be a sum of all (this *includes* the CPU) components' power added up, except your GPUs.
- the cost caused by this PowerOffset will be added to the GPU's power cost before checking profitability
- it affects mining only, if CheckProfitability is enabled.

**Comment by paulpoco** [comment]
So measure the PC at idle?

Onto the subject of CPU mining, in another thread someone said it the same reading at the wall with CPU mining or without.  I measure 50 to 65 Watts less when not CPU mining.  I am thinking of not CPU mining anymore but it would be nice if Rainbowminer only ran CPU mining if there was a large jump in profit.  Right now some are 2 cents a day profit.
