### ISSUE TITLE
Computer Logs Out and Logs Back In

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#466]
I'm wondering if you can help me with this weird problem that I only have on my rigs running RainbowMiner, it very well be that RM doesn't cause this though.  Sometimes my computers just logs out and logs back in, and RM isn't running when that happens.  It doesn't seem to be a crash but I've never seen anything like it.  Here are the Warnings and Errors from the Event Viewer right before this happens.  There are 3 of these errors:

-Error	3/11/2019 3:48:09 PM	DistributedCOM	10016	None
-The application-specific permission settings do not grant Local Launch permission for the COM Server application with CLSID 
{7022A3B3-D004-4F52-AF11-E9E987FEE25F}
 and APPID 
{ADA41B3C-C6FD-4A08-8CC1-D6EFDE67BE7D}
 to the user HHHH\hhhhC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.

and then 3 of these with Load and Unload alternating:

-Warning	3/11/2019 3:49:23 PM	User Profile Service	1534	None
-Profile notification of event Load for component {B31118B2-1F49-48E5-B6F5-BC21CAEC56FB} failed, error code is See Tracelogging for error details. 

Do these help, have you seen anything like this?  There is also a Warning about Windows Hello for Business but I'm not sure if it's relevant.

**Comment by thebeerbaron2018** [comment]
Sounds like Windows 10?  Probably a failed upgrade or something - try a Windows Update first and make sure that everything is successful - otherwise start there.

Failing that - it's the good old DCOM issues.  Try this link as a starting point - it's to do with Local Activation rather than Local Launch - but I'd put my finger on it that it's pretty similar (ie take a read through and understand what you're doing before blindly hacking at registry keys).

Always do a backup and a restore point!  

https://www.itexperience.net/2018/12/02/event-id-10016-fix-the-application-specific-permission-settings-do-not-grant-local-activation-permission-for-the-com-server-application-with-clsid/

Good luck.

**Comment by jch9678** [comment]
Thanks for the reply.  Yes, it's W10. I will get on the updates and yes there are a lot of DCOM warnings/errors in the event viewer.  The DCOM erros all have to do Windows Security Center, do you think if I install a 3rd party antivirus like avast they might go away?  I haven't had time to check out that site but I will, thank you again.

**Comment by thebeerbaron2018** [comment]
If they are antivirus related then installing a third party AV should turn off the Windows one and the errors MAY go away - but for a stable rig you probably want to be correcting the problem rather than trying to bypass it.
