### ISSUE TITLE
Bitcoin not accepted during install.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#467]
Did a Fresh install on a machine and as I was stepping though the questions I ran into the issue below. I simply removed it from the list and continued on.

`*** Selection Configuration ***

Hints:
- press Return to accept the defaults
- fields marked with * are mandatory
- use comma "," to separate list entries
- add new entries to a list, by adding a "+" in front of your input
- remove entries from a list, by adding a "-" in front of your input
- enter "list" or "help" to show a list of all valid entries
- enter "back" or "<" to repeat the last input
- enter "delete" to clear a non-mandatory entry
- enter "exit" or "cancel" to abort without any changes to the configuration

Enter the pools you want to mine [default=BlazePool]*:
Enter the miners your want to use (leave empty for all) [default=]:
Enter the miners you do want to exclude [default=]:
Exclude all miners with developer fee (yes/no) [default=no]:
Disable all dual mining algorithm (yes/no) [default=no]:
Enable conflict check if running CPU hungry GPU miners (for weak CPUs) (yes/no) [default=no]:
Enter the algorithm you want to mine (leave empty for all) [default=]:
Enter the algorithm you do want to exclude (leave empty for none) [default=Bitcoin,Blakecoin,BlakeVanilla,CryptoLight,CryptoNight,Decred,Keccak,KeccakC,Lbry,Lyra2RE,Lyra2RE2,MyriadGroestl,Nist5,Pascal,Quark,Qubit,Scrypt,ScryptN,SHA256d,SHA256t,Sia,Sib,X11,X13,X14,X15]:
The following entries are invalid (type "list" to show all valid):
Bitcoin

Enter the algorithm you do want to exclude (leave empty for none) [default=Bitcoin,Blakecoin,BlakeVanilla,CryptoLight,CryptoNight,Decred,Keccak,KeccakC,Lbry,Lyra2RE,Lyra2RE2,MyriadGroestl,Nist5,Pascal,Quark,Qubit,Scrypt,ScryptN,SHA256d,SHA256t,Sia,Sib,X11,X13,X14,X15]:
`

**Comment by jch9678** [comment]
This happened to me as well a few hours ago

**Comment by RainbowMiner** [comment]
Oh dear! sorry for that. Bitcoin is indeed invalid. Please remove it from the list using "-Bitcoin" - I will provide a fixed setup.

**Comment by RainbowMiner** [comment]
Thank you for reporting this issue. Fixed - please download (right-click save-as) the following two files into your .\Data folder and retry:
https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Data/ConfigDefault.ps1
https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/Data/algorithms.json

.. or wait for the next release :)

**Comment by jch9678** [comment]
The fix is confusing

Enter the algorithm you do want to exclude (leave empty for none) [default=Blakecoin,BlakeVanilla,CryptoLight,CryptoNight,Decred,Keccak,KeccakC,Lbry,Lyra2RE,Lyra2RE2,MyriadGroestl,Nist5,Pascal,Quark,Qubit,Scrypt,ScryptN,SHA256d,SHA256t,Sia,Sib,X11,X13,X14,X15]:

If you leave it empty, do you get none or do you get the default?

**Comment by jch9678** [comment]
Also i believe the " "s are missing around minimum mining interval when the config is produced.

**Comment by jch9678** [comment]
I'm getting this on a clean install of RainbowMiner:

PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'ReferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\sdsdsds\Desktop\RainbowMiner\Core.psm1:1187 char:97
+ ... rty Path -Unique) | Compare-Object @($Session.MinerFirewalls) | Where ...
+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\Users\sdsdsd\Desktop\RainbowMiner\Core.psm1:1187 char:97
+ ... rty Path -Unique) | Compare-Object @($Session.MinerFirewalls) | Where ...
+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

**Comment by RainbowMiner** [comment]
You are totally right, about the setup comment for the ExcludeAlgorithm. I will change this.
Regarding the cleaninstall error: I will fix this.
