### ISSUE TITLE
Burstcoin mining

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#494]
Is it possible to mine burstcoin from pools supporting hdd mining? If so how to configure properly or a guide would be great? I currently have downloaded qbundle and have everything configed correctly with online wallet activated and already made transaction. Any help would be great thanks?

**Comment by RainbowMiner** [comment]
Since this kind of mining works seamlessly in parallel to GPU mining, a good solution is to use RainbowMiner's autoexec feature to start the burstcoin mining. You will still have to setup Burstcoin on your own, since it includes the hdd plotting process.

There has been an issue by paulpoco where we discussed that. Eventually that helps: https://github.com/RainbowMiner/RainbowMiner/issues/261
