### ISSUE TITLE
Claymore's Miners

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#549]
Do you include claymore's miners anymore? I haven't seen any of them benchmark on any of my machines?

**Comment by RainbowMiner** [comment]
Yes, I do. Actually, in the coming release, there will be a new: ClaymoreEthashSC 
It's his new version v14.5 beta. Called "supercharged", where you may experiment with memory timings, on-the-fly.

**Comment by jch9678** [comment]
That's great news.
Could you check to see if claymore benchmarks on AMD cards? I haven't seen
it work in a long time. I don't have his miner excluded and Phoenix and
nanominer benchmark. I have ethminer excluded and it does not benchmark.

**Comment by RainbowMiner** [comment]
As far as I know, it benchmarks on AMD cards.
The old version is "ClaymoreEthash", running on Linux and Windows
The new version is called "ClaymoreDual", running on Windows, only

**Comment by jch9678** [comment]
I have dual mining disabled, could this be why it never benchmarks.

**Comment by RainbowMiner** [comment]
Yes, that has been the reason for the releases < v4.3.1.4 - the new release enables pure Ethash mining.

**Comment by jch9678** [comment]
Will rainbow miner apply the strap parameters and then benchmark or do we
need to do that ourselves?

**Comment by RainbowMiner** [comment]
Since the Claymore software is still in it's beta stage, I do not (yet) want to make it automatic.
In my opinion, at the moment, it runs too unstable, including very severe system crashes (I had to hard switch off and on my test rig many times, during my tests). 
Also the effect is stunning, these are the side-effects, I have experienced:
- an unsigned driver will be installed -> Windows 10 needs to run in "Testmode"
- the driver accepts one Claymore miner, only. If you want to run two, the second one will fail.
- if the driver is loaded, the share rejection rate and failures of many other miners spiked up
- overclocking seems to be changing, I cannot tell how, but the hashrate of other miners is down
- if you overclock and the stripe'd Claymore miner crashes, my rigs badly crashed in 75% of all cases.

**Comment by RainbowMiner** [comment]
So for now, you will have to decide for yourself, if it is worth, taking the risk.

If you add "-stripe 1" (or 2,3,4,5,6) to miners.config.txt and run RainbowMiner as admin, Claymore will install the driver and switch Win10 into testmode. You will have to reboot the pc to get it loaded.

**Comment by jch9678** [comment]
That is definitely not worth it.  Thanks for the explanation.  

> I cannot tell how, but the hashrate of other miners is down

Maybe his driver is affecting other algos negatively.

ClaymoreEthash and ClaymoreDual both benchmark now even though I have dual mining disabled.  Maybe that is the intended operation though.

**Comment by RainbowMiner** [comment]
"ClaymoreEthash and ClaymoreDual both benchmark now even though I have dual mining disabled. Maybe that is the intended operation though."

Yes, this is intended.
