### ISSUE TITLE
Help analyzing Activity Log

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#557]
I'm having trouble trying to figure out what RainbowMiner is doing.  It seems like there is too much switching and switching that shouldn't happen.  For example in the attached log RM switched from Phoenix to ClaymoreDual for seemingly no apparent reason; same algo, same pool MPH, potentially worse profit.  ClaymoreDual reported a 0 speed (not sure why) for 6 minutes and then switched back to Phoenix.  Phoenix mined for ~45 minutes, then switched to ClaymoreDual, same algo though at Nicehash this time.  After 6 minutes it then switched to Nanominer, at nicehash for definitely worse profit for 20 minutes.  Then tried ClaymoreEthash but speed was reported 0.  Looks like something might be wrong Claymore reporting 0 as well unless this is dev mining...

I have Switching Prevention set to 3.0, can you give us more information how this works,  I don't want to switch to a new algo/coin because of a minor change in btc profitability
 
By the way pressing S to skip switching prevention has never worked for me.
[Activity_2019-06-04.txt](https://github.com/RainbowMiner/RainbowMiner/files/3253162/Activity_2019-06-04.txt)

**Comment by RainbowMiner** [comment]
Could you eventually upload a Debug file? That makes analysis a lot's easier.

**Comment by jch9678** [comment]
Sure.  I changed the minimum mining interval to 45 and it has been mining for almost 24 hours straight.  The constant switching algos I think was putting a strain on the drivers.

[debug_2019-06-05.zip](https://github.com/RainbowMiner/RainbowMiner/files/3257662/debug_2019-06-05.zip)

**Comment by RainbowMiner** [comment]
It looks like that Phoenix has "breakdowns" in hashrate, where the total hashrate decreases from aprox. 180 to 125. This causes the watchdog to switch to another miner. I think, this is happening, during DAG switching.

This is copied from the Phoenix feature list:
* DAG file generation in the GPU for faster start-up and DAG epoch switches

Eventually this is happening for the other ethminers, as well.
I will increase the scan interval by factor of two. Eventually that handles the drops a bit more conservative. Also, I am thinking about some extra logic for algorithms, that rely on DAG like creation. It's a bit tricky, since there is now way to distinguish between that DAG related hashrate reduction and those caused by a crashed miner (or driver).

I think, best way for you to deal with it (especially since you are using one type of GPU, only, would be to allow only one ethash miner (and put the others on the ExcludeMinerName list).
In case of a miner update, you could re-enable the specific miner for rebenchmark.

**Comment by jch9678** [comment]
Ok thanks.  Pretty interesting stuff.  I will implement your suggestion.

Are you able to comment on the Switching Prevention numbers and not being able to Skip Switching Prevention by pressing S?
