### ISSUE TITLE
WARNING: RainbowMiner API is down!

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#634]
localhost:4000 not working after update 4.3.9.1

**Comment by RainbowMiner** [comment]
That's strange. Could you eventually send me a Debug file?

**Comment by RainbowMiner** [comment]
I found the problem. Please update both machines to the new version. Just remembered that I had build in a minor version check. Both machines need to be on the same minor version.
So if one machine is on v4.3.8.x and the other is on v4.3.9.x, they will not communicate.
Actually, I think I will remove this check. It should protect against incompatibilities on older machines, in the beginning. But now it turns out to be quiet useless.

**Comment by RainbowMiner** [comment]
Ohh! I need to revise my prior post. It's a warning caused by the downloader. That is quiet strange. Could you please click http://localhost:4000/downloadlist and send me the result, if it's different from "[]" ?

**Comment by RainbowMiner** [comment]
Also, eventually a restart of the rig solves the problem.

**Comment by hernandn01** [comment]
a rig restart cleared the problem, thanks
