### ISSUE TITLE
Issue: Miners.config missing Cpu miners

### ISSUE THREAD

**Issue by Byrd1083** [RainbowMiner/RainbowMiner#69]
I'm trying to manually set the intensity for the cpu miners to disable hyperthreading. However, all of the cpu miners are missing for cpujayydee and cputpruvot. Should double check and make sure there is not others missing.
[miners.config.txt](https://github.com/RainbowMiner/RainbowMiner/files/2340921/miners.config.txt)

**Comment by RainbowMiner** [comment]
The miners.config.txt is non-complete by design. My thoughts have been to provide a handful of miners, only, to enable an easy head-start. You should use the Configuration->Miners to add new entries. 

I could also program it, so that this list grows automatically, of course. What kept me from doing this: I fear that the list may grow to some size, over time, since new miners and algorithm will appear.
Anyway: I accept votes for this :)

RBM
