### ISSUE TITLE
Power offset percentage

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#704]
Please can the option to add a power offset as a % be added? I'm finding that generally my offset should be around 15%, but there's currently only the option to add a static value. For best results, perhaps both a % and a static value could be used concurrently?

**Comment by RainbowMiner** [comment]
Ok. I'll add this.

**Comment by RainbowMiner** [comment]
Added: 72f1bc637a4e596bd12dc75e80eac6ac85f4fd73

- add "PowerOffsetPercent" to config.txt
- during mining, the total poweroffset will be calculated with the following formula:
  `PowerOffset + CurrentPowerDraw * PowerOffsetPercent/100`

**Comment by samdave123** [comment]
I think this percentage value needs to directly affect algorithm profitability rather than the offset. A big power hungry algo like Ethash for example will be more affected than something like Cuckarood. Could this be factored into the profit-switcher?

**Comment by RainbowMiner** [comment]
Ah, ok. I understand, yes, that could be done.

**Comment by samdave123** [comment]
Isn't the profitability currently being calculated after RBM has chosen the most profitable algorithm? This is fine if the offset is a static value and affects all algorithms equally, but with a percentage value it will lead to algorithms being chosen which aren't necessarily the most profitable.

**Comment by RainbowMiner** [comment]
Yes, it is being calculated after the most profitable miners have been chosen.
Including that percentage into the profitability would not change a thing, I think. Please prove me wrong, if I happen to have a knot in my brain on this:

How it is calculated, right now:
```
TotalProfit[algo] = Hashrate[algo] * Poolprice[algo]
NetProfit[algo] = TotalProfit[algo] - PowerDraw[algo] * PowerPrice
```

How it would be calculated, with % offset in place:
```
TotalProfit[algo] = Hashrate[algo] * Poolprice[algo]
NetProfit[algo] = TotalProfit[algo] - PowerDraw[algo] * PowerPrice * ( 1 + PowerOffsetPercent )
```

Since `( 1 + PowerOffsetPercent )` is constant and the gradient `PowerDraw[algo] * PowerPrice` remains the same, it would only shift the characteristic line vertically, but would not change the position relative to each other algorithms.

**Comment by RainbowMiner** [comment]
RainbowMiner's strategy is as follows:
1. find the best pool for each possible algorithm. Result: list of `Algorithm => Pool`
2. calculate profit for each and every miner/algorithm combination. Result: list of `Miners`
3. sort `Miners` list by profitability
4. start mining the most profitable miner(s) on the most profitable pool(s)
