### ISSUE TITLE
Error on Start.

### ISSUE THREAD

**Issue by rhadamants** [RainbowMiner/RainbowMiner#714]
[RainbowMiner_2019-11-08_10-25-42.txt](https://github.com/RainbowMiner/RainbowMiner/files/3824777/RainbowMiner_2019-11-08_10-25-42.txt)

**Comment by RainbowMiner** [comment]
Oh! It looks like, you have some very old miners in your "Miners" folder (like CcminerBalloon, CcminerCool, etc). Since I have hugely optimized the miner modules, these old pals are no longer compatible.
Normally, the autoupdate should remove these automatically, so I suspect you have updated by hand by simply unzipping the newest version into your RainbowMiner folder.

Please try the following:
- stop RainbowMiner
- delete folders "Miners", "Pools", "APIs", "Balances"
- now unzip the most recent RainbowMiner release into your RainbowMiner folder

**Comment by RainbowMiner** [comment]
Please let me know, if that helped.

**Comment by rhadamants** [comment]
It works without problems now. I used auto update to try to fix this problem but it didn't work. But I really use the manual update.

**Comment by RainbowMiner** [comment]
Good to hear :) So I close this issue.
