### ISSUE TITLE
Web Interface stops responding.

### ISSUE THREAD

**Issue by Yamanipanuchi** [RainbowMiner/RainbowMiner#730]
I've had this happen on server machines. But primarily my server system, The web interface stops responding 2-3 times a day requiring my to complete re-start the script.
[debug_2019-11-14.zip](https://github.com/RainbowMiner/RainbowMiner/files/3848727/debug_2019-11-14.zip)

**Comment by acos0874** [comment]
I've experienced the same problem for the past week.

**Comment by RainbowMiner** [comment]
Can you eventually narrow it down, since when this is happening? I will investigate this asap.

**Comment by RainbowMiner** [comment]
Are there any Logs/errors_*.asyncloader.txt or Logs/errors_*.api.txt  files?

**Comment by Yamanipanuchi** [comment]
Wish I could narrow down a more exact time. It seemed to just creep up. At first I thought I just had a bad line in my config. But I did a complete RE-installed on the system I noticed it the most and the problem persisted.

[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/3852041/Logs.zip)

**Comment by RainbowMiner** [comment]
If you say stop responding, is it the whole computer, or is it just the API, which doesn't respond anymore? (e.g. http://locahost:4000 does not load anymore)

**Comment by acos0874** [comment]
Given enough time it becomes active again in my experienceSent from my Samsung Galaxy S9 - Powered by Three
-------- Original message --------From: RainbowMiner <notifications@github.com> Date: 15/11/2019  15:32  (GMT+00:00) To: RainbowMiner/RainbowMiner <RainbowMiner@noreply.github.com> Cc: acos0874 <acostello0874@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [RainbowMiner/RainbowMiner] Web Interface stops responding. (#730) If you say stop responding, is it the whole computer, or is it just the API, which doesn't respond anymore? (e.g. http://locahost:4000 does not load anymore)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RainbowMiner/RainbowMiner/issues/730?email_source=notifications\u0026email_token=AKE4DLFPHIAR3PSZ2I4QNELQT26HTA5CNFSM4JNSCSN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEFY5ZY#issuecomment-554405607",
"url": "https://github.com/RainbowMiner/RainbowMiner/issues/730?email_source=notifications\u0026email_token=AKE4DLFPHIAR3PSZ2I4QNELQT26HTA5CNFSM4JNSCSN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEFY5ZY#issuecomment-554405607",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Yamanipanuchi** [comment]
It would almost seem like its the API not responding.. System still mines away with no issues. I have not experienced the web part recovering, I usually end up Re-starting the script or system. I have started accessing the web interface and noticed it not responding and simply walked away for sometime and come back finding it still not responding.

**Comment by Yamanipanuchi** [comment]
Fresh logs off system that just stopped responding and before I have Re-started the system.
[Logs.zip](https://github.com/RainbowMiner/RainbowMiner/files/3852633/Logs.zip)

**Comment by RainbowMiner** [comment]
Could you try out the current [API.psm1](https://raw.githubusercontent.com/RainbowMiner/RainbowMiner/master/API.psm1) and overwrite the one from the last release? Just right-click and save to your server's RainbowMiner folder. Then restart RainbowMiner.

**Comment by RainbowMiner** [comment]
If the new API.psm1 does not resolve the problem, could you please set `"EnableMinerStatus": "0",` on your server? I want to be sure, that this function does not cause the trouble. Looking into the logs, it looks like, at some time, something bad happens between pinging the monitoring server and saving the stats.

**Comment by Yamanipanuchi** [comment]
Ok, I have the provided API.psm1 file in place. It will take time to see if it locks up again... Usually have 2-3 times a day. Ill give it 24 hrs and see. If it does lock up I will change the "EnableMinerStatus": "0", and let you know.

**Comment by RainbowMiner** [comment]
Super! Thank you so much.

**Comment by acos0874** [comment]
I just caught a lock up...

[errors_2019-11-16.api.txt](https://github.com/RainbowMiner/RainbowMiner/files/3854182/errors_2019-11-16.api.txt)

[errors_2019-11-16.asyncloader.txt](https://github.com/RainbowMiner/RainbowMiner/files/3854183/errors_2019-11-16.asyncloader.txt)

**Comment by acos0874** [comment]
It looks like it may be a memory issue...

![image](https://user-images.githubusercontent.com/42582444/68994906-decbfa00-087f-11ea-964b-1b494a573b1b.png)

**Comment by Yamanipanuchi** [comment]
So far with the provided api script i have not had the web interface stop responding. It usually would have by now.

**Comment by RainbowMiner** [comment]
@acos0874 please upgrade your Powershell to v6 - I think I remember a memory leak in PS5 that happened with a web request that failed with a webserver replying with non standard characters.

@Yamanipanuchi woa, so let's knock on wood and hope for the best! Thank you for your feedback!

**Comment by Yamanipanuchi** [comment]
I would consider the fix in the file
above worked. Web interface has not locked up once since i placed it.
