### ISSUE TITLE
Question about coins on pools

### ISSUE THREAD

**Issue by jch9678** [RainbowMiner/RainbowMiner#757]
Do all pools need to have coins listed in pools.config.txt?  I've been mining turtlecoin on MinerRocks but I just noticed trtl is not listed in pools.config.txt under MinerRocks...
[debug_2019-12-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/3937690/debug_2019-12-08.zip)

**Comment by RainbowMiner** [comment]
There needs to be a wallet connected to the pool. This can be done, either by directly adding it to the pools.config.txt or by setting `"EnableAutoCoin": "1",` in pools.config.txt plus `""EnableAutoPool": "1",` in coins.config.txt (what you did for MinerRocks)

**Comment by jch9678** [comment]
Cool.  I don't think I ever knew about that feature or maybe I just forgot.  I've enabled it in both those configs, now I just need to add a lot more wallets.

**Comment by Djago** [comment]
One more question regarding this.
My coins.config.txt have some coins with a defined wallet address (XMR, XWP and VRSC), but I have two coins without wallet address (ETH and RVN). Is this ok or all coins SHOULD have a wallet address?
I'm asking this because I want to add the possibility to mine FIRO in Zergpool (because my VEGA56 seems to be good to mine FIRO), but I don't want to be payed in FIRO, I prefer BTC, so I use the autoexchange feature.

**Comment by RainbowMiner** [comment]
If you use the autoexchange pools, you will need the selected autoexchange wallet (in your case BTC), only.
You only need real wallets for those coins, that you want to mine directly.

**Comment by Djago** [comment]
I'm on 7.1.2. No joy here. Still it doesn't recognize my key presses. I've also noted that now I can't click with the mouse in the console. Before this actual problem, if I mistakenly click over the console, a cursor block appeared and the console waited there for my enter key. That was a problem because sometimes when I inadvertently clicked on the console, the script just stopped waiting for me.
Now if I click over the console, nothing happens. I can RIGHT click and select an action from the menu (like selecting, copying and the like), but single left click won't do anything. I think this is related to the key press problem.

**Comment by Djago** [comment]
It's not that I want to mine directly, I want RBMiner to decide if it's profitable or not. Right now I have the EnableAutoCoin in 1, but my coins.config does not have any FIRO in there (not with nor without an address). And RBMiner does not list MTP in the console. I know that Teamred miner has correctly benchmarked MTP and I has a potential 2.82 MH/s. So I think it should be listed, or I am missing something?
