### ISSUE TITLE
GPU Dead

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#840]
Hi,

This is related to the earlier issue.

While mining GRIN the miner automatically kills 2 GPU's
as you can see from the screenshot 

This has forced me to disable GRIN on Ethashpool while mining for it

Please check what is the issue as my miners keep on picking it up as most profitable

![2 GPU Dead](https://user-images.githubusercontent.com/32984054/73041337-245e0200-3e83-11ea-8591-d16111da943d.png)

**Comment by saroshpatel09** [comment]
![GPU 1](https://user-images.githubusercontent.com/32984054/73041790-caf6d280-3e84-11ea-9cf1-84e253b4be95.png)
[gputestresult.txt](https://github.com/RainbowMiner/RainbowMiner/files/4106669/gputestresult.txt)
have uploaded a screenshot & gpurestresult.txt but the miner just kills 2 cards

**Comment by RainbowMiner** [comment]
Same issue: #839 

It's a pure Gminer issue. Since it hit's two different type of GPU, that should run hassle free, there are two possible causes, in my experience:
- overclocking is too harsh to handle the Cuckaroom29 algorithm
- Cuckaroom29 needs a lot of power, so maybe the power supply is too small

First, I would try to choose a reduced overclocking profile, try `"OCProfile": "Profile5",` in miners.config.txt, then Profile3. 

Ok, a third one, maybe it's a bug in Gminer.
