### ISSUE TITLE
All miners crashing

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#846]
All miners keep on crashing continously
[debug_2020-01-25.zip](https://github.com/RainbowMiner/RainbowMiner/files/4112122/debug_2020-01-25.zip)

**Comment by RainbowMiner** [comment]
In my experience, that has one of the following causes:
- "Lock P2 State" is not set to off
- Overclocking is too harsh
- Hardware failure, most likely one channel of your power supply units. In worst case, it may also be a GPU starting to fail.

This is what I would do:
- please verify, that the Nvidia "Lock P2 State" is set to off, use `.\\Includes\NvidiaProfileInspector\nvidiaProfileInspector.exe` to check and set it to off, if needed.
- change the PSU

**Comment by paulpoco** [comment]
@RainbowMiner is actually called "CUDA - Force P2 State".

Mine has been set to "on" forever, just changed to off.  Do need to reboot to take effect, I hit reply.

**Comment by RainbowMiner** [comment]
There are different states, a Nvidia GTX can operate. The states are set automatically, depending on the load. I have written an issue on that: #36

**Comment by RainbowMiner** [comment]
So, basically, you do not need to reboot. It's registered with the Nvidia drivers, after you hit the Apply button.

Each P state has its own cpu and memory clock, whereas the P0 state is the "full speed" state. If the Force P2 state is set to on, the drivers always try to run the GPUs in P2 state (lower clocks, compared to P0). If you now do set overclocking, using a try and error approach, you will end up with pretty high overclocking values, because you had experimenting on P2 state. 
If a miner starts operation, the GPUs might.switch to P0 state for a short period of time, until the automatic will force P2 state, again. 
During this blip, you will eventually end up with too high overclocking thus crashing the GPU and the miner.

Example: your GPU's max. memory clock is 8008MHz.
If the GPU runs at P2 state, the Nvidia drivers set the memory clock to 7202MHz
If the GPU runs in P0 state, the.Nvidia drivers set the.memory clock to 7600MHz
Through try and error, you figured out, +600 overlooking your GPU memory works out pretty.good (no wonder, since 7402 + 600 is pretty close to your GPU max).
Now as you start a.miner, the GPU shortly switches to P0: you would end up with a memory clock of 7600 + 800, which is far too high for your GPU. 
If.you are lucky, the period is too short and nothing happens. But you might as well crash the GPUs badly.

So, if you set Force P2 State to off, the GPUs will switch to P0, after the miner load peaks - and will stay on P0 state. All overclocking values will result in reliable clock totals.

**Comment by astronyu** [comment]
@RainbowMiner is it possible to show reason of crash in the dashboard? I sometimes have some miner crashing but not sure what causing it. Or is it too subjective?
