### ISSUE TITLE
Issue in Running

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#861]
Hi

Attached is then screenshot of what i am getting
please tell me what to do 

1. have restarted the miner
![Annotation 2020-01-30 080320](https://user-images.githubusercontent.com/32984054/73415203-30d8d380-4337-11ea-812f-0e52f79276f7.png)

2. have restarted the PC

**Comment by RainbowMiner** [comment]
Sorry for long wait for answer. I am currently on a business trip and have limited time. 
I would say, it's an overclocking issue. Ethash on Gminer and Claymore is pretty GPU memory intensive. Try to reduce the GPU memory overclocking value.

**Comment by qinapps** [comment]
I saw also following error messages:
Set-Stat : Cannot process argument transformation on parameter 'HashRate'. Cannot convert the "@{C31=214; C29d=5470}" value of type "System.Management.Automation.PSCustomObject" to type "System.Double".
At /home/prospector/RainbowMiner/Pools/Icemining.ps1:73 char:244
+ ... e -HashRate $(if ($Pool_CoinSymbol -eq "EPIC") {10} else {$PoolCoins_ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Set-Stat], ParameterBindingArgumentTransformationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-Stat

**Comment by qinapps** [comment]
also on Linux I can't setup from ground up.
When I use client mode and choose to download the config file from the server in the step where the selected pools are shown its goes in to a endless loop

**Comment by RainbowMiner** [comment]
Thank you for reporting. It looks like Icemining has changed the Cuckaroo reporting in their API. I will fix this.

Regarding the setup: could you eventually upload the logfiles in Logs folder? That would help me a lot in finding the cause.

**Comment by RainbowMiner** [comment]
Icemining is fixed, now.

**Comment by RainbowMiner** [comment]
> also on Linux I can't setup from ground up.
> When I use client mode and choose to download the config file from the server in the step where the selected pools are shown its goes in to a endless loop

.. could you eventually upload all "./Logs/RainbowMiner_*.txt" logfiles, that cover that setup time?

**Comment by qinapps** [comment]
@RainbowMiner sorry for the delay I was busy. 
On Linux I Have now that the AMD GPU are not found:"WARNING: No devices available. Running in pause mode, only. "
But in rocm-smi looks all good:"GPU[1] 		: WARNING: Empty SysFS value: pclk
1     N/A    11.0W    800Mhz  100Mhz  N/A            0.0%    auto    200.0W   0%        0%       0%"
I tried v4.5.3.1 and the newest

**Comment by qinapps** [comment]
when I run ./gputest.sh, I have following errors:
Exception calling "GetDeviceIDs" with "2" argument(s): "OpenCl error -1: DeviceNotFound."
At /home/minerstat/RainbowMiner/GPUtest.ps1:102 char:9
+         [OpenCl.Device]::GetDeviceIDs($_, [OpenCl.DeviceType]::All) | ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : OpenClException

**Comment by qinapps** [comment]
gputestresult:

GPU-TEST 02/15/2020 21:14:43
================================================================================


1. nvidia-smi
--------------------------------------------------------------------------------

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA d$

2. OpenCL
--------------------------------------------------------------------------------


Profile    : FULL_PROFILE
Version    : OpenCL 2.1 AMD-APP (2906.7)
Name       : AMD Accelerated Parallel Processing
Vendor     : Advanced Micro Devices, Inc.
Extensions : {cl_khr_icd, cl_amd_event_callback, cl_amd_offline_devices, }


................................................................................

**Comment by RainbowMiner** [comment]
You will need OpenCL support, if you try to mine with AMD GPUs.
Here is one tutorial of how to install OpenCL support:
https://linuxconfig.org/install-opencl-for-the-amdgpu-open-source-drivers-on-debian-and-ubuntu

.. if it doen't work out, maybe try [Google](https://www.google.com/search?q=amd+drivers+with+opencl+linux)

**Comment by qinapps** [comment]
the problem is bigger... on AMDGPU-PRO 19.50-967956 is ROCm OpenCL not working on the newest AMD GPU

**Comment by qinapps** [comment]
so all fixed: 
GPU-TEST 02/16/2020 23:48:19
================================================================================


1. nvidia-smi
--------------------------------------------------------------------------------

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and r$

2. OpenCL
--------------------------------------------------------------------------------


Profile    : FULL_PROFILE
Version    : OpenCL 2.1 AMD-APP (2906.7)
Name       : AMD Accelerated Parallel Processing
Vendor     : Advanced Micro Devices, Inc.
Extensions : {cl_khr_icd, cl_amd_event_callback, cl_amd_offline_devices, }



AddressBits                : 64
Available                  : True
CompilerAvailable          : True
DoubleFpConfig             : FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma
EndianLittle               : True
ErrorCorrectionSupport     : False
ExecCapabilities           : ExecKernel
Extensions                 : {cl_khr_fp64, cl_khr_global_int32_base_atomics, cl_khr_global_int32_extended_atomics, cl_khr_local_int32_ba$
GlobalMemCacheSize         : 16384
GlobalMemCacheType         : ReadWriteCache
GlobalMemCachelineSize     : 64
GlobalMemSize              : 8573157376

**Comment by qinapps** [comment]
but rbm still no device
