### ISSUE TITLE
MWC on Icemining

### ISSUE THREAD

**Issue by saroshpatel09** [RainbowMiner/RainbowMiner#929]
Hi,

MWC on icemining just doesnt bench..

says "Connection Error End Of File"

as and when you can please look into this..

**Comment by RainbowMiner** [comment]
Ok, I will look into it.

**Comment by RainbowMiner** [comment]
MWC is a beast of it's own :) I am currently updating the icemining pool module, so that the problems should be resolved soon.

**Comment by RainbowMiner** [comment]
Basically, you will have to supply a secure password, so that Icemining will be able to create a mining wallet for you - this password will be needed to withdraw MWC into your MWC wallet, as well.
Once the mining has started successfully, you may remove the password from your pools.config.txt. 
Everytime you change your MWC address, you will have to supply another password.

To supply this password, edit pools.config.txt, find the Icemining section and add your password like this:
```
  "MWC-Params": "putyourpasswordhere",
```

Note: this feature will be avail with the coming release v4.5.4.8

**Comment by saroshpatel09** [comment]
Bro also hope you can add frostypool.com if possible for MWC Cuckarood29

**Comment by saroshpatel09** [comment]
also for icemining no wallet is to be added to the pools.config.txt for MWC.?
and where on Icemining is the place to supply the password for the mining pool.? am unable to find it

**Comment by RainbowMiner** [comment]
> also for icemining no wallet is to be added to the pools.config.txt for MWC.?
> and where on Icemining is the place to supply the password for the mining pool.? am unable to find it


add this to Icemining section:
```
  "MWC": "yourmimblewimblewallet",
  "MWC-Params": "yourmwciceminingpassword",
```

**Comment by saroshpatel09** [comment]
i still dont understand about the password bro..

stay safe and stay home
