### ISSUE TITLE
Setup - start - first time user

### ISSUE THREAD

**Issue by imrecsoka** [RainbowMiner/RainbowMiner#966]
HI, i have run the start.bat file as administrator in windows 10 .
I have setup my api key in nicehash plugged it in to RM and also the Company ID
Same for miningpoolhub including username and api key.
Its my first time to do this, so please bear with me.
I then selected mostly default settings for RM setup.
It is supposedly starting to mine but it tell me :
WARNING: No pools available: check your configuration 
I dont know how to just do this simpler as Megaminer or MiningPoolHub Miner by Aaron.
Please can somebody help me or is there a video or something i can follow.
I have gone through the setup 2 times deleting all files unzipping the package and running he start.bat as admin.

**Comment by RainbowMiner** [comment]
Did you enter your BTC wallet address? 
You might want to upload a "Debug file", so that I can have a closer look:

Start RainbowMiner, even if it says "No pools available"
Open your Webbrowser to url http://localhost:4000
Now click "Debug file" on the left.

This will create a zip file, that you can safely upload here (all secret credentials are removed).
