### ISSUE TITLE
Profit/Benchmark Sheet Ordered

### ISSUE THREAD

**Issue by Adiuk** [RainbowMiner/RainbowMiner#988]
Is it possible to set, when in full mode, profit in value **order** of BTC Profit per day from top to bottom, it would make it easier to see what is most profitable at any given time as apposed to looking through the whole list, which at the moment it is not in any kind of order. Thank you

**Comment by RainbowMiner** [comment]
Is it adding a Profit column and automatic ordering the Benchmark list on localhost?
![image](https://user-images.githubusercontent.com/39437538/81673991-ca427600-944c-11ea-94d7-1f7838496f4f.png)

**Comment by Adiuk** [comment]
Not under benchmark as you have highlighted above
![image](https://user-images.githubusercontent.com/61330198/81674870-cbbc7000-9445-11ea-85bc-cf3daa0b2b64.png)

**Comment by acos0874** [comment]
I think you just need to look at the active miners tab?

**Comment by Adiuk** [comment]
I know that, I am talking about the powershell screen. So sometimes I just look at that for reference rather than going on the internet.

**Comment by RainbowMiner** [comment]
Ah! Now I get it. Ok, I'll add another parameter to config.txt, so that you can switch the sorting.

The lists are in fact sorted, currently: the benchmark list is sorted alphabetical by name, second by profit. The normal running list is sorted by biased profit (it's the internal switching algorithm).

**Comment by Adiuk** [comment]
Excellent thank you
